### ISSUE TITLE
Props don't get updated for custom event handelrs

### ISSUE THREAD

**Issue by glennsl** [reasonml/reason-react#102]
Given this (heavily reduced) component:

```rust
  let make ::count ::onChange _children => {

    let handleClick _ => {
      onChange (count + 1)
    };

    {
      ...component,

      didMount: fun self => {
        /* assume `element` has been acquired by legit means */
        element##addEventListener "click" handleClick;
        ReasonReact.NoUpdate
      },

      render: fun self =>
         ...
    }
  };
```

`onChange` will never be called with anything other than `1`, regardless of what the `count` prop is changed to. The reason is of course that `make` will be called again on props change, which will define a new `handleClick` function that closes over the new prop value, but will not (and obviously should not) call `didMount` again to attach the updated event handler. So the old event handler with the old prop value will be called in perpetuity.

This isn't all that surprising if you understand how RR actually works, but it is if you expect it to work like reactjs' `this.props` (which of course I did, even though I should know better). RR creates the illusion, and thereby expectation, that it does work like `this.props`, until of course it doesn't. I suggest that this is made clear in the documentation somewhere, even if just as a FAQ.

There are two workarounds, neither of which are very nice:

1. Copy the prop to state (or retainedProps?), and use state in the event handler instead.
2. Remove and re-attach the event handler on `didUpdate`. This would also involve maintaining state to keep a reference of the currently attached event handler for removal, but is a more contained solution and good practice regardless of needing updated props, in case the element is re-inserted.

This seems like a fundamental restriction with the API as it currently is, but I wanted to bring it up so  perhaps it can be addressed in some future iteration at least.

Full example here: https://github.com/glennsl/rr-stale-props-issue/blob/abb81215857d4240b5bfd748dbb28e4d98590d33/src/index.re

**Comment by chenglou** [comment]
cc @cristianoc @jordwalke @rickyvetter

**Comment by cristianoc** [comment]
My way of looking at things is that RR does not have props. It has state. And willReceiveProps really means will receive state.
