### ISSUE TITLE
[Docs] Is there a tutorial similar to Angular's "Tour of Heroes"?

### ISSUE THREAD

**Issue by isthisnagee** [reasonml/reason-react#104]
👋 Not sure if this is the right place to put this, but I'm just starting to use reason-react and I feel like a guided tutorial would be a nice way of getting introduced to the ecosystem.

Angular has this really nice [Tour of Heroes](https://angular.io/tutorial) tutorial. It's is a relatively comprehensive guide that goes through a lot of the Angular core and its best practices. I'm not very familiar with react-reason (or reasonml in general) and I'm wondering if something like the Tour of Heroes exists or if someone is working on something similar. If not, I'd love to star this effort.

**Comment by OlegLustenko** [comment]
Or maybe some tour similar to Go-lang

**Comment by davesnx** [comment]
Super old issue, but there's a magnific book similar to the Tour of Heroes: https://react-book.melange.re

I would close this issue for reference and, it's technically resolved.

Thanks @isthisnagee
