### ISSUE TITLE
Document subscription patterns

### ISSUE THREAD

**Issue by rickyvetter** [reasonml/reason-react#115]
We should look into first-classing as much as possible here, but once we've gotten to where we are comfortable we should document how deal with various sub/release apis. They very widely and some are more friendly to our React patterns than others.

**Comment by glennsl** [comment]
This is somewhat related to #102 as well I think.

**Comment by rickyvetter** [comment]
Agreed. #102 is a specific case of what I’m worried about here - where RR is less intuitive than React JS. We need to either design this case away or provide clear instruction.

**Comment by alexfedoseev** [comment]
@rickyvetter @chenglou @glennsl On #102 case: AFAICT w/ current api it can be handled by copying props to state and wrapping handler w/ `self.handle` before passing it to `window.addEventListener`. Should this be added to docs? Or there's a better way to handle this?
