### ISSUE TITLE
Update docs for interop with ES6 modules

### ISSUE THREAD

**Issue by nwaywood** [reasonml/reason-react#116]
Creating this issue by the request of @chenglou from the following discussion we had on discord:

![image](https://user-images.githubusercontent.com/3773641/32421586-4ad07b06-c2ee-11e7-8462-8f5acd9dad2f.png)

The docs [here](https://reasonml.github.io/reason-react/docs/en/reason-using-js.html) and [here](https://reasonml.github.io/reason-react/docs/en/interop.html#reactjs-using-reasonreact) only show how to interop with ES5 modules.

If you guys would like I'd be happy to submit a PR updating these docs, let me know

**Comment by peterpme** [comment]
For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Please re-open if this is still relevant. Thanks!
