### ISSUE TITLE
Document Common Errors

### ISSUE THREAD

**Issue by jaredly** [reasonml/reason-react#12]
Here are some I made :D 

- a `make` function that just returns jsx (not the component spread)
- a `make` function that doesn't have a final `_children` arg (the error is super inscrutable)

**Comment by jaredly** [comment]
Would be awesome if we could get BetterErrors to give help when coming across these.
(which raises for me the question of a generic "enhanced error hints" setup that libraries could plug into....)

**Comment by AgtLucas** [comment]
We should add those here: https://reasonml.github.io/reason-react/#reason-react-common-type-errors

**Comment by chenglou** [comment]
Done done done
