### ISSUE TITLE
How to use ocaml syntax with reason-react?

### ISSUE THREAD

**Issue by doofin** [reasonml/reason-react#125]
It seems that bsb only provides build-in react support via reason syntax

**Comment by jordwalke** [comment]
I think we might need to do a little bit of refactoring to make it so that we you end up with a usable API without relying on any of our built-in ppx plugins.  We're definitely open to it.

**Comment by chenglou** [comment]
@doofin you can't have JSX since that's a Reason-specific syntax; however, you can use the desugared form, or this PPX: https://github.com/cxa/ppx_bsx

The rest of ReasonReact works as expected in vanilla OCaml.

Closing! Ping me if you got further questions =)

**Comment by shinzui** [comment]
Should ppx_bsx be part of the reason-react project? It does not look like it's maintained.
