### ISSUE TITLE
Inconsistency between min and max type

### ISSUE THREAD

**Issue by thangngoc89** [reasonml/reason-react#137]
Currently, min accepts `int` and max accepts `string`. I think they should have the same type which is `string`.

This is a valid syntax: ` <input type="date" name="bday" min="2000-01-02">` 

@chenglou I can send a quick PR to fix the type of min to string if you want. Could you confirm on this?

**Comment by chenglou** [comment]
Sure! Thanks.

**Comment by dusterherz** [comment]
Any news on this issue ? Had the same problem with date inputs.

**Comment by peterpme** [comment]
For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Please re-open if this is still relevant. Thanks!
