### ISSUE TITLE
Having to use stringToElement() is awkward

### ISSUE THREAD

**Issue by gaearon** [reasonml/reason-react#138]
See this thread: https://mobile.twitter.com/Stealtheritz/status/938224539330326528
Warning: subjective opinions ahead!

This doesn't impact me directly, but having to use `stringToElement()` to add text always felt like "appeasing the compiler" kind of work that I would expect from a language like Java, not Reason. :-)

I have two issues with this API:

1. I want to just use strings.
2. The naming doesn't match my knowledge of React. A string is *not* an element. An element is an object that looks like `{type, props}`. A string is a string. You can't turn it into an element. A string *is* a React node though. You don't need to convert it to a node—a string is already a valid React node type. But if the compiler insists, I could see myself writing `ReasonReact.text()` for this.

By the way, I know I can write `let s = ReasonReact.stringToElement()` at the top. This feels like an afterthought to me. Yes, I could, but this just disguises the fact that the API is not ergonomic.

**Comment by pseudoramble** [comment]
This is also somewhat related - [The docs here](https://reasonml.github.io/reason-react/docs/en/jsx.html) make it seem like it should be possible to do this:

> **Note that due to current syntax constraints, you need to put spaces around the JSX children:** `<div> foo </div>`.

It could help to point out why it's needed and perhaps point out the trick of making an alias to the function with a shorter name.

**Comment by aaronshaf** [comment]
FWIW in internationalized apps we'll already want to write something else over it, i.e.

```reason
let i18n = FormatMessage.translate |> ReasonReact.stringToElement
```

```jsx
<div className="title">
  (i18n("What to do"))
</div>
```

**Comment by kujon** [comment]
Part of what makes Reason/OCaml great imho, is the lack of type coercion. The cognitive load is low, you don't have to learn tons of magic rules like in JS, you have to be explicit. Introducing an exception just for React risks taking Reason from the familiar syntax, into familiar syntax and behaviour territory. And the behaviour in JS is what makes it such a mad language sometimes.

Personally, 👎 to most of the proposal, however this bit:
> But if the compiler insists, I could see myself writing ReasonReact.text() for this.
looks very sensible.

**Comment by cnguy** [comment]
@kujon Latest version of ReasonReact supports `ReasonReact.string()` now!

**Comment by skosch** [comment]
`ReasonReact.string()` isn't the solution, and redefining it at the top isn't either.

> Introducing an exception just for React risks taking Reason from the familiar syntax, into familiar syntax and behaviour territory. And the behaviour in JS is what makes it such a mad language sometimes.

JSX *is* the exception. It's markup, not code. Nobody has ever complained about JSX being a mad language; it was never broken, and it didn't need ~fixing~ type checking. The only thing that's mad here is having to tell the compiler that a literal hard-coded string really is ... drum roll ... a string.

Is there a technical reason we can't have standard JSX? With all (sincere!) gratitude and respect to the Reason team, what keeps you from addressing an issue that has nearly 50 thumbs-ups and is clearly a big turn-off for potential newcomers? Is there anything that can be done to help?

**Comment by cristianoc** [comment]
https://github.com/facebook/reason/pull/1910

**Comment by gaearon** [comment]
Can I ask Reason experts to clarify what this has to do with type coercion?

I don’t propose to *coerce* string to an object. I think what I’m proposing is more like making a node to be a union type of string and element. Which is my mental model from actual React.

**Comment by kujon** [comment]
> JSX is the exception. It's markup, not code. Nobody has ever complained about JSX being a mad language; it was never broken, and it didn't need fixing type checking. The only thing that's mad here is having to tell the compiler that a literal hard-coded string really is ... drum roll ... a string.

JSX is just a syntax sugar for `createElement`. In JS, you can do put almost anything as a child:

```js
React.createElement('div', null, false);
React.createElement('div', null, 42);
React.createElement('div', null, 'dsadasd');
```

All Reason is doing here is just telling you that a child must be an array of React elements and putting you in charge of converting your data structures to it.

This is not that different to how you perform other conversions:

```re
/* won't work */
let foo = "4" ++ 4;

/* this will */
let foo = "4" ++ string_of_int(4);
```

IMHO, we shouldn't try to make Reason behave like JS, because (as a JS guy myself), I feel like we've got a lot to learn from the OCaml community about how type-safe code works.

**Comment by skosch** [comment]
So, not having looked into this in nearly enough depth – is this, in the end, simply a limitation of OCaml's type checker? I.e., that @gaearon's "union type of string and element" simply can't be done without explicit type annotations of some sort, because OCaml neither provides type introspection nor typeclasses-like polymorphism that will implicitly pick the right instance? And therefore standard JSX behaviour is just completely out of reach, at least with the current ppx infrastructure?

**Comment by cristianoc** [comment]
@skosch that's correct.
We're looking in what's the smallest extension that would give us this feature, and ideally have other applications as well.

**Comment by texastoland** [comment]
> Can I ask Reason experts to clarify what this has to do with type coercion?

@gaearon I'm not an expert but I think I can explain.

> I think what I’m proposing is more like making a node to be a union type of string and element.

It sounds like you're thinking `type node = 'a element | string`. But in MLs (OCaml, Haskell, etc.) the branches are named with constructors like `type node = Element('a) | Text(string)`. You can already see the latter in ReasonReact:

https://github.com/reasonml/reason-react/blob/9e344b8a059ca82e88ca575bebc60abb9deac0d8/ReactMini/src/React.re#L57-L59.

Right now `ReactElement.string` is a little lie. It's a type coercion to `reactElement`:

https://github.com/reasonml/reason-react/blob/9e0d5c3159eb35b619e532964ceb30737667d8a5/src/ReasonReact.re#L20

Although JSX is a ppx (compiler macro) it sounds like from https://github.com/facebook/reason/pull/1910#issuecomment-391564779 it doesn't receive typings so it could only coerce literals.

I agree it's too much typing for newcomers.

**Comment by peterpme** [comment]
@gaearon This has been fixed and is now `{React.string("hi dan")}`

Would love to have you give Reason another go-around :smile: Thanks!

Closing out for now.

**Comment by MoOx** [comment]
Even better imo `{"Hi Dan"->React.string}` :)
