### ISSUE TITLE
Incorrect module path with es6_global

### ISSUE THREAD

**Issue by ghost** [reasonml/reason-react#139]
I am trying to design a development workflow leveraging the fact that browsers are starting to support es6 modules. The idea would be not to use a bundler during development, relying on bsb -make-world -w and browser refreshes.

I use es6_global package spec in order to have full paths so that the browser can resolve modules correctly.
It actually works wonders and is a joy to use.

However it breaks down with reason-react which injects a dependency on react in a way that relies on nodejs module resolution algorithm.

Is there a way to resolve the relative path to react when using es6_global ?

**Comment by chenglou** [comment]
@Meshu I'd love that too, but that'd be a reactjs issue right? https://github.com/facebook/react/issues/11503

**Comment by chenglou** [comment]
Np! Welcome =)

Keeping this issue open til we get es6 exports from reactjs

**Comment by chenglou** [comment]
eh, cc @acdlite
