### ISSUE TITLE
Missing `pointerEvents` style attribute

### ISSUE THREAD

**Issue by jaredly** [reasonml/reason-react#14]

**Comment by AgtLucas** [comment]
@jaredly are you sure? https://github.com/reasonml/reason-react/blob/master/src/reactDOMRe.re#L408 🤔

**Comment by glennsl** [comment]
@AgtLucas That's the prop. SVG CSS properties are largely missing: https://github.com/reasonml/reason-react/blob/master/src/reactDOMRe.re#L915

As are lots of others. It's just a matter of adding them.

**Comment by AgtLucas** [comment]
@glennsl Ah, I see. I'll add then. :)

**Comment by chenglou** [comment]
Do these above 2 solve this?

**Comment by jaredly** [comment]
yup this is solved
