### ISSUE TITLE
Automatically convert bool to Js.Boolean

### ISSUE THREAD

**Issue by aaronshaf** [reasonml/reason-react#141]
on properties that expect a Js.Boolean. This would eliminate the need to do:

```jsx
<input
  _type="checkbox"
  checked=(Js.Boolean.to_js_boolean(item.completed))
/>
```

**Comment by cristianoc** [comment]
There's a more fundamental change being worked on, where the distinction between Js.boolean and bool will disappear entirely.

**Comment by aaronshaf** [comment]
Is this a branch we can look at? Thanks!

**Comment by wegry** [comment]
https://bucklescript.github.io/blog/2018/04/16/release-3-0-0.html removed the distinction between bool and Js.boolean.
