### ISSUE TITLE
Kill ref & key

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason-react#144]
This will allow us to kill the entire `ReasonReact.element` wrapper, which would reduce a lot of complexity.

**Comment by cullophid** [comment]
How would that work?
Killing ref would not be that big of a deal, you can just use the dom api, but key is quite important when rendering list items (unless something has changed since last i checked :))

**Comment by peterpme** [comment]
For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Please re-open if this is still relevant. Thanks!
