### ISSUE TITLE
'wrapJsForReason should convert idiomatic OCaml optional args into JavaScript nullable props'

### ISSUE THREAD

**Issue by thangngoc89** [reasonml/reason-react#149]
I'm trying to write a binding for Menu component of AntDesign

Here is the TypeScript Props definition

https://github.com/ant-design/ant-design/blob/fdf0c11ec78200e18d12d1a8bd3886936a6d1891/components/menu/index.tsx#L25-L46

On first attempt, I followed the bindings like in the official documentation:

```reason
[@bs.module] external myJSReactClass : ReasonReact.reactClass = "myJSReactClass";

let make = (~name: string, ~age: option(int)=?, children) =>
  ReasonReact.wrapJsForReason(
    ~reactClass=myJSReactClass,
    ~props={"name": name, "age": Js.Nullable.from_opt(age)},
    children
  );
```

But this has a problem that `age` is passed as part of props with `undefined` value.

If in JS land, you do a check to know if the user passed `age` prop or not like this:

```js
"age" in this.props // === true
a.hasOwnProperty("age")  // ===true
```

For example in the above Menu component:

https://github.com/ant-design/ant-design/blob/fdf0c11ec78200e18d12d1a8bd3886936a6d1891/components/menu/index.tsx#L70-L87

With the help of @yawaramin on Discord, I came up with binding : 

https://gist.github.com/thangngoc89/8299569b6983de543419c23d497ee377#file-menu-re-L1-L96

IMHO, that's too much boilerplate. wrapJsForReason should some how handle this internally.

from @yawaramin on Discord
>  you can say something like 'wrapJsForReason should convert idiomatic OCaml optional args into JavaScript nullable props'

**Comment by rickyvetter** [comment]
This is addressed with BS changes and react.component externals.
