### ISSUE TITLE
[Docs] Provide documentation/FAQ about HOCs (Higher Order Components)

### ISSUE THREAD

**Issue by emmenko** [reasonml/reason-react#154]
Hey guys,

I think it would be really helpful in general to have some information about what to do with HOCs (e.g. spreading props, etc), mostly because it should not be necessary to have HOCs in Reason.

There are a couple of good blog posts out there that already describe the problems and the solutions when dealing with HOCs. Additionally it would be easier to have a page in the official documentation instead of searching through Discord.

The blog posts I mean are:
* https://jaredforsyth.com/2017/11/12/advanced-reasonreact-hider-order-components/
* https://medium.com/@_gabrielrubens/binding-a-react-hoc-to-reasonml-children-as-function-d2688e4edaae

Pinging @chenglou @jaredly @grsabreu as the authors of mentioned blog posts / discord discussions.

Do you think it would make sense?
I could start writing down the page but you guys have definitely more knowledge about this.

Thanks in advance! 🙏

**Comment by Voronar** [comment]
[A popular pattern in React is the higher-order component pattern, so it’s important that we can provide effective types for higher-order components in Flow.](https://flow.org/en/docs/react/hoc/)
`TypeScript` and `Flow` allowing to types HOC's very properly and I think it is a big advantage versus `Reason`.

**Comment by peterpme** [comment]
For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Please re-open if this is still relevant. Thanks!
