### ISSUE TITLE
JSX explicit optional ref and key not transformed correctly

### ISSUE THREAD

**Issue by glennsl** [reasonml/reason-react#16]
As mentioned on Discord.

Even if they're manually added to the js props object, they will be overwritten by `wrapProps` here: https://github.com/reasonml/reason-react/blob/master/src/reasonReact.re#L551

The simplest solution might be to add `::ref` and `::key` to `wrapJsForReason` and pass them on to `wrapProps`

**Comment by glennsl** [comment]
This is apparently a ppx bug and has nothing to do with wrapProps. Should I close this and file a new issue, or rebrand this one? @chenglou

**Comment by chenglou** [comment]
I'd say keep it open until we land it the next release

**Comment by glennsl** [comment]
Ok, would you like to edit the title and description so we get it right? I'm not sure about the specifics.

**Comment by chenglou** [comment]
Done. https://github.com/facebook/reason/pull/1309

**Comment by chenglou** [comment]
Fixed by bs-platform 1.8.0
