### ISSUE TITLE
Add React.Fragment FFI

### ISSUE THREAD

**Issue by thangngoc89** [reasonml/reason-react#162]
This is my current binding: 

```reason
// Fragment.re
[@bs.module "react"] external reactClass : ReasonReact.reactClass = "Fragment";

let make = children =>
  ReasonReact.wrapJsForReason(~reactClass, ~props=Js.Obj.empty(), children);
```

I'm not sure where to put this in a PR so I opened an  issue instead

**Comment by thangngoc89** [comment]
@geraldodev please don’t ask random questions in issues

**Comment by geraldodev** [comment]
@thangngoc89 

Did that in the spirity of learning. A copy and paste of your code, with another class that is not typed.

**Comment by sslotsky** [comment]
This change is in a PR currently https://github.com/reasonml/reason-react/pull/151/files

Any chance of getting it merged? Looks quite helpful!

**Comment by naartjie** [comment]
I think this can be closed now. There is now a way to do `React.Fragment` in Reason-React.

Docs: https://reasonml.github.io/reason-react/docs/en/jsx#fragment

**Comment by phated** [comment]
This is now available in the `React` module - https://github.com/reasonml/reason-react/blob/master/src/React.re#L77
