### ISSUE TITLE
Getting started react theme broken

### ISSUE THREAD

**Issue by BrendanBall** [reasonml/reason-react#168]
following the basic steps on https://reasonml.github.io/reason-react/docs/en/installation.html
```
npm install -g bs-platform
bsb -init my-react-app -theme react
cd my-react-app && npm install && npm start
# in another tab
npm run webpack
```
running `yarn start` results in more than a page of compiler errors.

**Comment by BrendanBall** [comment]
see https://gist.github.com/BrendanBall/e31ea61e41ee744e45c0708c8035958f . I would think you should be able to reproduce it by running it yourself as it seems to do with the syntax changes to reasonml.

**Comment by chenglou** [comment]
I can't repro it. Do you happen to have a stale lockfile somewhere? What's your bs-platform version?

**Comment by BrendanBall** [comment]
Ah found my issue. I seem to have installed `bs-platform` with `npm` a while ago which was overriding my `yarn` version of `bs-platform`. so it was using `bs-platform` version 2.0.0 instead of version 2.1.0. still not sure why version 2.0.0 is broken because I would've expected the corresponding package.json to install a working version of the bs compiler, but that's not really important.
