### ISSUE TITLE
simplify subscriptions api

### ISSUE THREAD

**Issue by aappddeevv** [reasonml/reason-react#173]
I was working with some subscriptions but realized that the API may be able to be simplified to something like `Unit => Unit => Unit`. That way reasonreact gets out of the token storage/closure business.

**Comment by saboya** [comment]
It still has to store the callback reference bound to the first callback scope, so I don't think this is better at all.

**Comment by cullophid** [comment]
I think the idea is that the teardown function would store context in a clojure

**Comment by aappddeevv** [comment]
That's correct, you can store it yourself. In fact, the reasonreact code creates its own closure and stores it, so getting out of the token storage business would simplify the code in that area with no real extra burden on the user.

**Comment by chenglou** [comment]
Sorry, not too sure what you mean; can you give an example?

**Comment by cullophid** [comment]
Something like:
```
let documentClickSubscription = () => {
  let handler = Document.on(`click, someFunc);
  () => Doccument.off(`click, handler);
};
```

**Comment by chenglou** [comment]
Interesting! @aappddeevv does that look right?

**Comment by aappddeevv** [comment]
Yes!

**Comment by chenglou** [comment]
What if we just used a imperative API instead?

```reason
let handler = Document.on(`click, someFunc);
self.register(() => Doccument.off(`click, handler));
```

Then we can remove subscriptions altogether (with deprecation warnings of course)? You'd be able to register them from anywhere in any lifecycle, etc.

**Comment by flash-gordon** [comment]
@chenglou this doesn't look helpful tbh. When subscriptions were released I already had a simple pub/sub system in my app so having a proper place for them was really nice, I happily removed quite a bit of boilerplate with adding a one-line adapter for new ReasonReact subscriptions. A big advantage of the new approach was having a compiler check so that you don't forget to unsubscribe, ever. With your proposal, this is still possible but not so evident. Maybe having both APIs is an option, although no one asked for an imperative API yet :)

**Comment by chenglou** [comment]
You'd still get the compiler warning if you do `Document.on(`click, someFunc);` without assigning it to something (it doesn't now; that's a bug/feature in the Reason syntax we can fix). I think the subscription API's semantic wasn't clear and doesn't catch most of the cases of e.g. `setTimeout`, and whatever else happens in specific places outside of `subscriptions`.

**Comment by flash-gordon** [comment]
Well, I do agree this sounds reasonable, my use cases are more about lifetime subscriptions:

```reason
  subscriptions: ({state: {actions, wire}}) => [
    actions.sub(Storage.persist(wire)),
    actions.sub(AppEvent.transform(events)),
    events.sub(Router.listen(router))
  ],
```
^
This lives in a top-level component and looks declarative enough :) I know internally it will be executed in a sequential order in `didMount` but I'm OK with that. I can live with `didMount` and `self.register` for sure, but I usually use it for truly side-effect-ish things at the moment (e.g. fetching remote data) so I don't have a semantic problem here.

**Comment by chenglou** [comment]
Right, so you've already made your registration wrappers; that's even easier I believe. After the change it'd look like:

```
didMount: self => {
  ReasonReact.register(Storage.persist2(wire));
  ReasonReact.register(AppEvent.transform(events));
  ReasonReact.register(Router.listen(router));
}
```

Note that there will be no more need for understanding the` ReasonReact.Sub()` GADT anymore.

**Comment by cullophid** [comment]
You could just have:
```
subscriptions:[
  documentClickSubscription
  ...
  ]
```

**Comment by flash-gordon** [comment]
@chenglou there is a subtle conceptual problem with `didMount` in this regard. It has to return a `ReasonReact.update` value and this confuses me. Should I return `NoUpdate`? Or should I return `SideEffects` with a lambda where I put all three subscriptions? It'd be more consistent to return `unit` from `didMount` and make updates explicit with `send` IMO.

**Comment by chenglou** [comment]
@cullophid can't; some of these need access to `self`, thus the function.

@flash-gordon see the note here: https://reasonml.github.io/reason-react/docs/en/lifecycles.html. You should always return `NoUpdate`.

**Comment by jordwalke** [comment]
With the current API, it seems to remove a lot more possibility for error (pit of success).
```
subscriptions: (self) => [
    Sub(
      () => Js.Global.setInterval(() => Js.log("hello!"), 1000),
      Js.Global.clearInterval
    )
  ],
```

You'd have to try harder to get a handle on the subscription token, since RR internalizes it entirely. That means it would be hard to accidentally double-unregister it etc. I'd be fine with an imperative API if there's other benefits, but either way I like when the API encourages you to put the creation/tear down next to each other so you aren't tempted to split them apart in the code, and they get out of sync in some way. Is there an imperative API that has all the benefits of the current API?

**Comment by chenglou** [comment]
The current one doesn't cover lots of other cases, like `setTimeout` (unless you literally just want a `setTimeout` on didMount for some reason), async requests, etc. These still need to be stored on the state, aka people still don't do it. The new API trades off some small pit of success for a larger one.

**Comment by aappddeevv** [comment]
Keeping together is nice. You really cannot solve the async "I forgot to do clear it" problem using any of the APIs being discussed. You would have to provided an "Async" object that is provided as API in order to guarantee teardown when something happens to the component. But that seems like a larger step.

**Comment by chenglou** [comment]
`ReasonReact.register` does solve the problem though?

**Comment by chenglou** [comment]
It's not the same:

```reason
ReasonReact.UpdateWithSideEffects(
  newState,
  self => Js.Global.setTimeout(() => self.send(Foo), 1000)
);
```

This currently generates a warning, and can't be caught using the subscriptions API. The `register` API would catch it.

**Comment by chenglou** [comment]
After simulating this internally, it indeed catches _all_ the leaky subscriptions. I'm convinced we should go with this. `self.subscribe`/`self.register` name proposal?

**Comment by rickyvetter** [comment]
I'd prefer not to use self.subscribe since so many subscriptions use that keyword already. Gets overloaded in situations like:

```
let handler = foo.subscribe("eh", someFunc);
self.subscribe(() => foo.release("eh", handler));
```

Register runs into the same potential confusion but is much rarer.

**Comment by chenglou** [comment]
Fair enough. The idea we want to convey is that it will clean up your subscriptions implicitly in willUnmount, whenever you use it. `register` isn't that ideal; got better ideas?

**Comment by chenglou** [comment]
Here's a realistic use-case:

```reason
didMount: self => {
  let sub1 =
    Thread.subscribeToMessage((_, data) =>
      self.send(Received(data))
    );
  let sub2 =
    Thread.subscribeToDeletion((_, data) =>
      self.send(Deleted(data))
    );
  self.register(() => Thread.unsubscribe(sub1));
  self.register(() => Thread.unsubscribe(sub2));
},
```

Whichever name we pick, we might also expose a convenience `registerMany` that takes an array.

Admittedly this API doesn't shine here vs the old one, but all the e.g. async requests from `UpdateWithSideEffects` and `SideEffects` in reducers are now caught! Let's make sure the naming makes sense there too

**Comment by rickyvetter** [comment]
I kinda like the super explicit `onUnmount`:

```js
didMount: self => {
  let sub1 =
    Thread.subscribeToMessage((_, data) =>
      self.send(Received(data))
    );
  let sub2 =
    Thread.subscribeToDeletion((_, data) =>
      self.send(Deleted(data))
    );
  self.onUnmount(() => Thread.unsubscribe(sub1));
  self.onUnmount(() => Thread.unsubscribe(sub2));
},
```

**Comment by glennsl** [comment]
This is pretty much equivalent to Go's `defer`, except it's scoped to component lifecycle instead of function lifecycle. So maybe `self.defer(() => ...)`?

**Comment by rickyvetter** [comment]
Note that this API can also allow you the super declarative style that the current API has if you define a function `mountSubscriptions` (for cases where you are only doing those subscriptions in the didMount):

```js
didMount: mountSubscriptions(self => [
  Sub(
    () =>
      Thread.subscribeToMessage((_, data) =>
        self.send(Received(data))
      ),
    Thread.unsubscribe,
  ),
  Sub(
    () =>
      Thread.subscribeToDeletion((_, data) =>
        self.send(Deleted(data))
      ),
    Thread.unsubscribe,
  ),
]),
```

**Comment by chenglou** [comment]
`onUnmount`: sounds good, but I'm super scared that it'll be misunderstood/abused as `self.onUnmount(() => Logger.log("hello"))`. Plus if you accidentally call that `onUnmount` many times thinking it's idempotent. I guess that's your problem, but still, this is a problem not present in the current API, though the current API can't cover such situation (registering an unregistration in a closure or anywhere outside of didMount) at all.

`defer`: this sounds a bit like `throttle` too much imo

**Comment by glennsl** [comment]
> we might also expose a convenience registerMany.

What benefit would that yield that this wouldn't?
```ml
self.register(() => {
  unsub1();
  unusb2();
});
```

vs (I imagine)

```ml
self.registerMany([unsub1, unsub2]);
```

**Comment by chenglou** [comment]
Oh yeah true lol. Nvm.

**Comment by glennsl** [comment]
> defer: this sounds a bit like throttle too much imo

I don't really see why, but if you want to be extremely explicit you could use `deferToUnmount` instead. But I prefer `defer...` over `on...` because it's more prescriptive.

**Comment by rickyvetter** [comment]
The only reason I recommended `onUnmount` is that it is very explicit about behavior and timing. `defer` by itself is less explicit about timing but perhaps more explicit about the behavior. `deferToUnmount`/`deferUntilUnmount` (to feels awkward to me - usually I would defer to a person, but defer until a time) is pretty verbose, but definitely has a very exact meaning.

[Lodash uses defer](https://lodash.com/docs/4.17.5#defer) as a kind of next tick operation so I think if we use defer we should be a little more explicit - maybe `self` is enough context? It's possible that's where @chenglou is getting the `throttle` similarities from.

**Comment by glennsl** [comment]
Le me just preface by saying that I think `deferToUnmount`/`deferUntilUnmount` is _good enough_<sup>:tm:</sup>. It's a safe choice, but I also think it's unnecessarily explicit, for two reasons which I think is interesting to consider more generally:

1. While perhaps not a central concept, I'd say it's an important concept that will be frequently used in RR development. It's not just some random function in a massive utility library. And I think it's unlikely to be used without first having gone through the documentation and learnt about the concept already.

2. I think it's unlikely to be misunderstood in the context it will be used. `defer` would be a function tightly associated to the component via `self`. And in the context of a component, what could it possibly mean? I suppose it could mean "defer until next render", or "until next reduce", but does it seem likely that this interpretation would seem more natural than "defer until unmount"?

> Lodash uses defer as a kind of next tick operation

Interesting. This seems to have exactly the same meaning as this and Go's `defer`, just with a different scope. I can definitely see how this could lead you to group it in with other "timing-functions" though.

**Comment by rickyvetter** [comment]
Couple concerns I have with defer:

1. Is the word and meaning familiar to non-native English speakers?
2. Is there a chance we would want to use defer at the language level or for a different purpose in the RR library (defer rendering, defer state updates, etc)?

If the answer for 1 is yes and 2 is no then I think `defer` is good.

> I prefer defer... over on... because it's more prescriptive

> I'm super scared that it'll be misunderstood/abused as self.onUnmount(...

These sound like very similar arguments and I'd love to hear why you think this is a bad thing. IMO willUnmount should only ever be called for cleanup and potential logging. It makes sense that all of that stuff would have a dual in some other lifecycle/handler. If we removed `willUnmount` and replaced with `self.onUnmount` would that be a negative?

**Comment by flash-gordon** [comment]
@chenglou now we have `onUnmount`, okay, but will the old `subscriptions` API be removed in the next version? Or is it not decided yet?

**Comment by chenglou** [comment]
It’ll be removed. The one one’s slightly more imperative, but catches strictly more cases and has an api that doesn’t require understanding of GADT and other confusing stuff.
