### ISSUE TITLE
Docs - Change SVG favicon to PNG

### ISSUE THREAD

**Issue by markus-willems** [reasonml/reason-react#181]
Is it possible to change the favicon from SVG to PNG (as it is for the normal [Reason Docs](https://reasonml.github.io/))?

Currently only Firefox (fully) supports the use of SVG as favicon: https://caniuse.com/#feat=link-icon-svg

In my bookmarks bar I only display the favicons (no text) and that standard Chromium icon really messes with my OCD :smile:

```html
<link rel="shortcut icon" href="/reason-react/img/reason-react-red.svg"/>
```

**Comment by matejstrasek** [comment]
This can be closed as https://github.com/reasonml/reason-react/pull/207 was merged.

**Comment by chenglou** [comment]
Thanks!
