### ISSUE TITLE
No local server preferred option of installation is a bad idea

### ISSUE THREAD

**Issue by tbsvttr** [reasonml/reason-react#182]
I would argue that not setting up a local server is really a bad idea and bad practice. It will lead to a lot of problems for which some people will blame Reason or ReasonReact. This will be an easy fix.

For example [in Chrome React Developer Tools will only work with additional configuration](https://github.com/facebook/react-devtools/blob/master/README.md#the-react-tab-doesnt-show-up).

**Comment by peterpme** [comment]
For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Please re-open if this is still relevant. Thanks!
