### ISSUE TITLE
Improve documentation re Router url.search

### ISSUE THREAD

**Issue by fremontmj** [reasonml/reason-react#189]
The current documentation at https://reasonml.github.io/reason-react/docs/en/router.html says:
```
So the url www.hello.com/book/10/edit#author?name=Jane is given back as:
{
  path: ["book", "10", "edit"],
  hash: "author",
  search: "name=jane"
}
```

This appears not to be currently true, at least in Mac Chrome v64.0.3282.167.  

When I do this:
```
ReasonReact.Router.push("test/#ZombificationPage?levelNumber=50")
```
and then look at the url object returned to my listener, I get an empty search field and a hash with the query in it.

Looking at the code in ReasonReact.re, there is this comment:
```
/* sigh URLSearchParams doesn't work on IE11, edge16, etc. */
  /* actually you know what, not gonna provide search for now. It's a mess.
     We'll let users roll their own solution/data structure for now */
```

which seems to acknowledge the problem.

Indeed, in the Chrome debugger when I interrogate the location object, I get
```
location.hash = "#ZombificationPage?levelNumber=50"
location.search = ""
```
So I can understand the frustration in the comment!

Perhaps the documentation could reflect this reality?

**Comment by chenglou** [comment]
Actually, that comment might not be related. This might be a bug?

**Comment by chenglou** [comment]
Actually, that example's wrong. The URL should be `www.hello.com/book/10/edit?name=Jane#author` if I'm not mistaken

**Comment by kennetpostigo** [comment]
Yea hash should be the last portion of the URL always I believe

**Comment by chenglou** [comment]
Thanks for the confirmation!
