### ISSUE TITLE
Show usage warnings during compile

### ISSUE THREAD

**Issue by yawaramin** [reasonml/reason-react#190]
Some parts of the ReasonReact public API are really escape hatches and should not really be used, as much as possible. Currently we are 'informally' warning users about these APIs, e.g. #99 

I propose adding explicit `[@warning]` attributes to these places to show these warnings during compile, when they will be most effective. Here are a couple of places I've identified:

- `ReactDOMRe.createDomElement`
- `ReasonReact.jsElementWrapped`
- `ReasonReact.handedOffState` (in the record type `componentSpec`)
- `ReasonReact.Router.dangerouslyGetInitialUrl`

There may be more I missed?

The user would have to explicitly turn off the warning if they use these APIs, e.g. with `[@warning "-foo"]`.

**Comment by chenglou** [comment]
Does putting warning attribute on individual record fields actually work? Didn't last time I tried.

`ReasonReact.Router.dangerouslyGetInitialUrl` is actually needed in quite a few cases, just that it needs to be carefully used.

`createDomElement`: are you talking about `ReasonReact.createDomElement` or `ReactDOMRe.createElement`? Both are used (latter by JSX, former by https://reasonml.github.io/reason-react/docs/en/jsx.html#uncapitalized

(I do put warning and deprecation attributes on whatever I can =))

**Comment by yawaramin** [comment]
> Does putting warning attribute on individual record fields actually work?

Good question, based on https://caml.inria.fr/pub/docs/manual-ocaml-4.06/extn.html#sec260 it may not. I'll check.

> `ReasonReact.Router.dangerouslyGetInitialUrl`

IMHO if it's really needed, but it's obviously dangerous, it's still good to warn users. They can always suppress the warning explicitly at the location of use.

> ... are you talking about `ReasonReact.createDomElement` or `ReactDOMRe.createElement`?

Hmm, I was talking about the latter specifically because we already warned about it in #99. But if JSX desugars into a bunch of calls to these functions, it may not make sense for them to have compiler warnings.
