### ISSUE TITLE
Feature: Add ReasonReact.listToElement

### ISSUE THREAD

**Issue by mimshwright** [reasonml/reason-react#192]
Just to simplify the conversion process further.
`listToElement : list(reactElement) => arrayToElement(Array.of_list(list))`

**Comment by cullophid** [comment]
Yay

**Comment by mimshwright** [comment]
hmm. looks like perhaps this is defined in `reason-react/ReactMini/src/React.re` but not included in the ReasonReact module? Is that intentional?

**Comment by mimshwright** [comment]
Oops, this is a duplicate of #140

**Comment by chenglou** [comment]
ReactMini is a small experiment that has not much to do with ReasonReact itself and isn't shipped

**Comment by chenglou** [comment]
This really kills perf and is not recommended

**Comment by djyde** [comment]
So what is the best practice

**Comment by cullophid** [comment]
But react children are a result of rendering application state. So that means changing all the lists in your app to arrays. 
By doing so you are sacrificing immutability.
I have seen quite a few newcomers pick arrays over lists just for this reason.

**Comment by viktor-izettle** [comment]
Would also be nice with a few more. For example `ReasonReact.int`. It gets old quickly to always convert all these common types.

**Comment by praveenperera** [comment]
> Use array. React children should probably not be modeled as a list

Does that mean this

```reasonml
[1,2,3]
-> Belt.List.map((num) => <div> string_of_int(num) </div>
-> Belt.List.toArray
-> ReasonReact.array
```

Is slower than

```reasonml
[1,2,3]
-> Belt.List.toArray
-> Belt.Array.map((num) => <div> string_of_int(num) </div>
-> ReasonReact.array
```

**Comment by IwanKaramazow** [comment]
The problem is that `Belt.List.toArray` traverses the whole list and adds its elements (one by one) to an array. That extra traversal can be avoided by using plain arrays.

**Comment by praveenperera** [comment]
@IwanKaramazow 

> The problem is that `Belt.List.toArray` traverses the whole list and adds its elements (one by one) to an array. That extra traversal can be avoided by using plain arrays.

Oh I see, so it might make sense to model the underlying data into arrays instead of lists from the start? For example decoding a list of users from the server, into an array instead of a list.

**Comment by IwanKaramazow** [comment]
Yes indeed, modelling everything as array from the start is indeed recommended.
