### ISSUE TITLE
[JSX] Desugar aria'foo to aria-foo for DOM elements

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason-react#196]
Actual transformer's in the Reason repo.

**Comment by rafayepes** [comment]
Also `data'foo` to `data-foo`?

**Comment by yawaramin** [comment]
Yup, it should be a general transformation of `foo'bar` -> `foo-bar`.

**Comment by chenglou** [comment]
I'm thinking maybe we can just use `ariaFoo` -> `aria-foo` and `dataFoo` -> `data-foo`. Again, this is on DOM elements only, so no confusion of e.g. accepting ariaFoo in a custom component prop and do things with it.

**Comment by yawaramin** [comment]
Could DOM elements potentially not have camelCased attribute names?

**Comment by chenglou** [comment]
We’d only be doing it for aria and data

**Comment by yawaramin** [comment]
Oh, I was imagining it would be simpler to check for the `foo'bar` form and convert it directly into `"foo-bar"`, am I missing something?

**Comment by chenglou** [comment]
Either is simple enough. But are you saying that we might as well go with `'` since it generalizes to e.g. `svg'set` (nonexistent prop) instead of just `data'foo` or `aria'foo`? Though those other kebab-cased props don't exist, unless someone's trying to pass a custom dom prop

**Comment by yawaramin** [comment]
Exactly, we can fully support any potential kebab-cased prop names thanks to `'`, which is great since kebab-cased attribute names are valid HTML. This would bring JSX more in line with valid HTML.

**Comment by chenglou** [comment]
My main nitpicky concern is that it's ugly and we don't want to encourage over-usage of `'` in prop names in Reason. But since this seems to be the only way to enable custom props, then let's do it.

**Comment by yawaramin** [comment]
I think real-world use will be minimal. Kebab-cased attrs are pretty rare (unless you're using Angular 1 or something). In practice this will be just a nice escape hatch, not a heavily-used feature.

**Comment by chenglou** [comment]
It's mandatory for a11y because of aria

**Comment by yawaramin** [comment]
Ya, but that's usually a minority of all JSX attributes.

**Comment by chenglou** [comment]
Related: we might find a good aria-* solution anyway with https://github.com/BuckleScript/bucklescript/issues/2614

**Comment by alexfedoseev** [comment]
I dunno, this doesn't seem ugly to me:

<img width="401" alt="screen shot 2018-03-14 at 15 56 40" src="https://user-images.githubusercontent.com/4244251/37389773-8ab5258e-27a0-11e8-8b32-70b9f86e4d6b.png">

But when camelCase is used for everything:

```
dataTestid
onClick
```

it seems inconsistent a bit.

**Comment by chenglou** [comment]
Fixed in 0.4.2 thanks to `bs.deriving abstract`.

I'll open another issue for `data-*`, though I tend to just let folks use cloneElement

**Comment by alexfedoseev** [comment]
Please, desugar `data-*` too, otherwise it’s required to clone every control from standard components (like `Button` and other interactive elements) to make them findable in integration tests.
