### ISSUE TITLE
Error : "The field send does not belong to type ReasonReact.self"

### ISSUE THREAD

**Issue by MawsFr** [reasonml/reason-react#198]
Hello guys 😄 

I don't really know were to post this but i'll try here 

I am a newbie to Reason react and I'm struggling on an error that I can't correct right now
I am on windows and when I add the `bs-fetch` and the glenn's `bs-json` package to my project I can't build it anymore with `bsb -make-world`

I get an error saying that  "The variant constructor Js.Exn.Error can't be found."

Here is a screenshots of my ide with all concerned files

![code_2018-03-04_19-22-04](https://user-images.githubusercontent.com/4595534/37149947-2e6f7ff6-22d0-11e8-8cb8-ef388f7c74f9.png)

I work with 3 other students and we all have the same problem (I tested on mac and it builds perfectly even with the mentionned packages ^^)

If you need any other information please ask ^^

you could need this :
```Shell
C:\Windows\System32>node -v
v8.9.1

C:\Windows\System32>npm -version
5.7.1

C:\Windows\System32>npm version
{ npm: '5.7.1',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.9.1',
  openssl: '1.0.2m',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.15.0',
  v8: '6.1.534.47',
  zlib: '1.2.11' }
```

Thank you 👍

**Comment by chenglou** [comment]
Hello! Can you give a small repro repository please?

**Comment by bloodyowl** [comment]
@MawsFr you are using `reason-react@0.2.4`, the `send` API appeared in `0.3.1`

**Comment by chenglou** [comment]
lockfiles ¯\_(ツ)_/¯

I'll consider this resolved for now!

**Comment by MawsFr** [comment]
Sorry i was busy with the end of my studies. Indeed updating my packages with `ncu -u` did resolve my problem :)

Thank you !
