### ISSUE TITLE
Reserved keywords in JSX underscore appended rather than prepended

### ISSUE THREAD

**Issue by tmepple** [reasonml/reason-react#204]
Same issue as https://github.com/facebook/reason/issues/1840 but filed here as the code exists in this repo.

I believe the JSX props that collide with reserved keywords should have the underscore appended rather than prepended as it's more idiomatic and trips up newbies (like me)!  

So `<input _type="email">` would become `<input type_="email">`.  Looking at `ReactDOMRe.re` it seems _open, _begin, _end, _in, and _to are similarly affected.

It's especially confusing since the nice error message you get at this point says `Error: 34: type is a reserved keyword, it cannot be used as an identifier. Try 'type_' instead` but when you follow that advice you get a long error including `This argument cannot be applied with label ~type_`.  It took a while and I had to eventually look at the source to figure it out.  Prepended underscores usually mean the identifier is not intended to be used in the scope -- which silences compiler warnings.  Overloading this meaning increases cognitive load for newbies.

Since it would be a breaking change, assume both `type_` and `_type` should be supported until next major version but unsure how to generate deprecation warnings.  I also couldn't find where the mangling from "_type" to "type" for the final html actually occurs (bucklescript?, reactjs?) so I didn't know how to make a PR to address.  Thanks!

**Comment by chenglou** [comment]
Fixed. We now accept the appended version. Prepended ones such as `_type` are now deprecated: https://github.com/reasonml/reason-react/blob/master/HISTORY.md#042
