### ISSUE TITLE
Ability to extend a component

### ISSUE THREAD

**Issue by mciparelli** [reasonml/reason-react#209]
It would be nice to have the ability to extend a component by providing some default values for example. I tried to extend `TextInput` but I noticed there's no way for me to create CustomTextInput without having to redefine bindings for TextInput, even oif CustomTextInput takes a single extra prop

**Comment by chenglou** [comment]
Hi! Extending a component is discouraged, likewise in ReactJS. The solution is indeed to use TextInput in CustomTextInput under the hood. We also don't support props spread for the same reason (perf, predictability). Sorry about that
