### ISSUE TITLE
Unclear behaviour of JSX and ReactElements

### ISSUE THREAD

**Issue by MarcCoquand** [reasonml/reason-react#215]
If you define a pure component like you normally could in Javascript like so:

```
let ugh = (~text="none", ~onClick) =>
  <button onClick> (ReasonReact.stringToElement(text)) </button>;
```

and then in the render function have the following code:
```
      <ugh onClick=(_e => self.send(Click)) />
```

The code will compile without any errors but will not display the button. However if you use:

```
     (ugh(~onClick=(_e => self.send(Click)))
```
the code compiles fine and displays the button. It would be nice if the compiler warned about this behaviour (or allowed us to render ReactElements with < />).

**Comment by rickyvetter** [comment]
If you switch to the new hooks api this now works! Your component can be called with JSX.
