### ISSUE TITLE
Revisit wrapJsForReason with bs.abstract

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason-react#216]
Probably a much better way of binding to js objects.

**Comment by chenglou** [comment]
cc @thangngoc89 and your blog post

**Comment by thangngoc89** [comment]
I didn’t read much about bs.abstract but bs.as is what I have waiting for

**Comment by chenglou** [comment]
Potential change: include `children`. Make `make` children labeled.

```reason
let make = children =>
  ReasonReact.wrapJsForReason(
    ~reactClass=spinner,
    ~props=Js.Obj.empty(),
    children,
  );
```

No more questions around `Js.Obj.empty()` either.
