### ISSUE TITLE
Confusing handling of "event.target.value" for Form/Input elements

### ISSUE THREAD

**Issue by rrdelaney** [reasonml/reason-react#218]
One of the more confusing things I've heard has been that getting the actual value from an `<input />` is kind of confusing, especially when coming from React (JS) or Angular. These are the current docs:

> ReasonReact events map cleanly to ReactJS synthetic events. More info in the inline docs.
>
> If you're accessing fields on your event object, like event.target.value, you'd use a combination of a ReactDOMRe helper and BuckleScript's ## object access FFI:
>
> ```rust
> ReactDOMRe.domElementToObj(ReactEventRe.Form.target(event))##value;
> ```
> More info on the ReactDOMRe module below in the Working with DOM section.

having to call two functions and then use the `##` syntax can be a lot for a new comer just looking to find a simple translation for code they know.

I think one way around this might be a `ReactDOMRe.unsafeGetValue`, which could looks like:

```rust 
let unsafeGetValue : Form.t => string = [%raw (event) => "{return event.target.value}"];
```

Thoughts?

**Comment by mmiszy** [comment]
You could also use `[@bs.get]`:

```reason
[@bs.get] external unsafe_targetValue : (Form.t) => string = "target.value";
```

**Comment by chenglou** [comment]
Is it just Form? Anything else with a target with a value field?

**Comment by rrdelaney** [comment]
`value` is a property on:

* `<button>`
* `<input>`
* `<li>`
* `<option>`
* `<progress>`
* `<param>`

Which should be covered by `ReactEventRe.Form`, right?

**Comment by rrdelaney** [comment]
What about maybe “unsafeTargetValue” that returns “target.value” as a string? I think that would be the most common operation to do with target anyway using it a Js.t

**Comment by chenglou** [comment]
I think `ReactEventRe.Form.targetUnsafe(event)##value` is more applicable, since otherwise you'd need a specific binding for each, and `target` is infinitely polymorphic.

Also, `targetUnsafe(foo)##bar` doesn't generate extra code.

**Comment by rrdelaney** [comment]
Oh wait, I might have missed something.. with Js.t({..}) can you access any key name and it will infer the type from usage?

**Comment by chenglou** [comment]
Yeah basically `ReactDOMRe.domElementToObj`

**Comment by rrdelaney** [comment]
Oohhh that makes way more sense now 😁 I thought users would have to manually write a converter to a string, and couldn’t just access it. “unsafeTarget” or something like that sounds great then

**Comment by justgage** [comment]
So what exactly is "unsafe" about assuming the target is going to be there on an `onInput` event? I think even a little helper function would make a huge difference, is this open for a PR?

**Comment by chenglou** [comment]
It's unsafe because this might not be the case

**Comment by chenglou** [comment]
Been fixed since the newest release. Instead of unsafeTarget, I've made a new ReactEvent module. Please see the blog post and history.md for migration script and details. Thanks!

**Comment by banacorn** [comment]
I'm getting `null` from `ReactEvent.Form.target(event)` in some cases.
Should the returned type be `nullable(Js.t(<..>))` instead of just `Js.t(<..>)`?

**Comment by bloodyowl** [comment]
@banacorn Do you execute `ReactEvent.Form.target(event)` in an async callback (such as `setState(() => ...)`? This is the most common mistake with React events, they are pooled to reduce memory pressure: the record still exists, but all properties are emptied right after the event handler call.

If that's the case, instead of:

```reason
<input
  value
  onChange={event => setValue(_ => event->ReactEvent.Form.target##value)}
/>
```

you might want to do:

```reason
<input
  value
  onChange={event => {
    let value = event->ReactEvent.Form.target##value;
    setValue(_ => value)
  }}
/>
```

**Comment by banacorn** [comment]
@bloodyowl wow that's a speedy response!

Yes, that's exactly the mistake I made! Thank you!
