### ISSUE TITLE
Unwarranted JSX close tag causes first character of file to be an error

### ISSUE THREAD

**Issue by canadaduane** [reasonml/reason-react#221]
If you have a file with the following content (note unwarrnated `</svg>` close tag):

```
/* First character marked as error */

let make = _children => {
  ...component,
  render: _self =>
    <div className="App">
      </svg>
    </div>,
};
```

the first character of the file will be marked as an error. It would be helpful if the parser could identify the actual cause of the problem (line 7 in this example) rather than mark the whole file as "bad".

**Comment by rickyvetter** [comment]
Looks like this is fixed in the 3.1.0 version of Reason - new error:

```
Line 6:5-Line 7:12 Start tag <div> does not match end tag </svg>
```
