### ISSUE TITLE
The module structure for react components conceals mistakes

### ISSUE THREAD

**Issue by aloifolia** [reasonml/reason-react#222]
The current approach of declaring new components as modules with certain variables is both elegant and error-prone. If I do certain things wrong, I will not get a (helpful) compiler error message. Two of which would be:

- if I forget to include crucial parts (like `component`) the compiler gets confused because it does not recognize other parts correctly any more (like `initialState`)
- if parts of the code have the wrong type this is not necessarily shown in this file (on the definition site) but somewhere else in my code (on the call site); `initialState` is a candidate for this problem

Is there a way to avoid these kinds of mistakes altogether? For me as a beginner, these kinds of issues seem to be both avertable and time-consuming enough to devise a solution.

**Comment by rickyvetter** [comment]
I believe the new api does a much better job of making things work for beginners. You are much less likely to run into a type error while writing a component.
