### ISSUE TITLE
Weird failure to compile

### ISSUE THREAD

**Issue by Tevinthuku** [reasonml/reason-react#229]
Im getting this error in the screenshot below
![screenshot from 2018-05-26 10-45-51](https://user-images.githubusercontent.com/12128153/40573947-277484f4-60d2-11e8-9451-6003375eee92.png)

I dont know how to fix it. 
Im running Ubuntu 18

**Comment by Tevinthuku** [comment]
My bsconfig looks like so

```js
{
  "name": "creativesanctuary",
  "sources": ["reasoncomponents"],
  "bs-dependencies": ["reason-react"],
  "reason": {
    "react-jsx": 2
  },
  "package-specs": {
    "module": "commonjs",
    "in-source": true
  },
  "suffix": ".bs.js",
  "bsc-flags": ["-bs-super-errors"],
  "refmt": 3
}

```

**Comment by chenglou** [comment]
Hey! Do you have a repro repo?

**Comment by Tevinthuku** [comment]
Yeah, whenever I try to install it locally I get this error
![screenshot from 2018-05-27 09-26-54](https://user-images.githubusercontent.com/12128153/40583110-350338c2-6190-11e8-9505-bd0b99a52097.png)

**Comment by chenglou** [comment]
cc @bobzhang this isn't the same error as the other day, but maybe similar

**Comment by Tevinthuku** [comment]
I dont have opam installed though, could it be the reason for this error ?

**Comment by chenglou** [comment]
You don't need opam for this

**Comment by Tevinthuku** [comment]
I found a way of making it work by changing the directory of the project folder
it works when I place the folder in the root of the Documents directory like so
```
~/home/tev/Documents
```

but if its deeply nested like this
```
~/home/tev/Documents/Projects/***/***
```
it doesn't work..

**Comment by arecvlohe** [comment]
@chenglou I am running into the same issue. What do you mean by "you should be using a local bs-platform"? How do I get the project to run the local dep and not the globally installed one?

**Comment by arecvlohe** [comment]
Here is one of my relevant errors:

```
[1/3] Building src/Component1-ReactTemplate.cmj
FAILED: src/Component1-ReactTemplate.cmj /Users/arecvlohe/Desktop/Native Projects/my-react-app/src/Component1.bs.js src/Component1-ReactTemplate.cmi
/Users/arecvlohe/.nvm/versions/node/v8.9.4/lib/node_modules/bs-platform/lib/bsc.exe -bs-package-map react-template  -bs-package-output commonjs:src -bs-assume-no-mli -bs-no-builtin-ppx-ml -bs-no-implicit-include -I /Users/arecvlohe/Desktop/Native Projects/my-react-app/node_modules/reason-react/lib/ocaml -I . -I src  -w -30-40+6+7+27+32..39+44+45+101 -bs-suffix -nostdlib -I '/Users/arecvlohe/Desktop/Native Projects/my-react-app/node_modules/bs-platform/lib/ocaml' -no-alias-deps -color always -bs-re-out -bs-super-errors -o src/Component1-ReactTemplate.cmj -c  src/Component1.mlast
/Users/arecvlohe/.nvm/versions/node/v8.9.4/lib/node_modules/bs-platform/lib/bsc.exe: don't know what to do with Projects/my-react-app/node_modules/reason-react/lib/ocaml.
Usage: bsc <options> <files>
Options are:
```

**Comment by arecvlohe** [comment]
@chenglou My errors had to do with the file system. I am on a Mac OS X and when the folder name has a space in it like I had, Native Projects, it did not load correctly. When I changed the folder name to NativeProjects it worked as expected.

**Comment by arecvlohe** [comment]
@Tevinthuku You might be experiencing the same issue. I see one of your folder names has a space in between, `CREATIVES SANCUARY`.

**Comment by Tevinthuku** [comment]
I think I can close this now, Im also able to add the bs-platform to my dev dependencies successfully
