### ISSUE TITLE
reducerComponent initialState error in the wrong place

### ISSUE THREAD

**Issue by mudrz** [reasonml/reason-react#232]
[repro: https://reasonml.github.io](https://reasonml.github.io/en/try.html?rrjsx=true&reason=LYewJgrgNgpgBAIQIYCc4F44G8BQc6wAucAxiMAA4gB2M1xmASjEgM43NImEB0KMkEjBQBhclVr0AFACJkKGQEoA3HgIxiwJAGt4mKQH1FGAHzY1+HlbKUadQgBoLcAPQAqZ-jgBLAGY-qb0JvJCgAZUIkQnhvVjhqEGJvahIoCDABJy9swgALeGEUEDRYuFZckAB3agC4PPgSUKhkgHNScHgpADEQEEUs7Pxk1mikMDgQf3z+OCl5RWc3F2d3AKCQ8MjogC5Z43QzGRkHOCXnfkFhXcNdkZRWk4NbwnvqFv2zTnZqTm4eADkQABVChgKIwAb4fjUDIoXYGVgwKD+A5wAA8YG8ADczFIvhwWH87q1ZPIlMY0S5MTiBgBfVT0nA4UCQWBwHogDDmfBEdq2SQMOD4n6E3gjcGwVisMT8+yyDlKVQ8jRwLS6LkGEi5bxQMDQ0zcrxWHg2CT2SFwaGw+GI5EGjHYsxo+SuJ1Ux10hmqHC-QgAEQA8gBZZh8OiwgAqIAAorBgPYAOpBXIASTAUjRHNdJxkFH4WO8MEqipwQA)

minimal code:
```reason
module Bar = {
  let component = ReasonReact.reducerComponent("Bar");
  let make = (_) => {
    ...component,
    /*
       if initialState is not included,
       the error is shown in the calling code (Foo),
       instead of here (Bar)
    */
    /* initialState: () => "", */
    reducer: (_: string, _: string) => ReasonReact.NoUpdate,
    render: _self => <div> (ReasonReact.string("Bar")) </div>,
  };
};

module Foo = {
  let component = ReasonReact.statelessComponent("Foo");
  let make = _children => {
    ...component,
    render: _self => <div> <Bar /> </div>,
  };
};

ReactDOMRe.renderToElementWithId(<Foo />, "preview");
```

Possibly also related https://github.com/reasonml/reason-react/issues/222

Furthermore the error is unclear:
```
This has type:
  (string, ReasonReact.stateless, ReasonReact.noRetainedProps,
   ReasonReact.noRetainedProps, string)
  ReasonReact.componentSpec
But somewhere wanted:
  (string, 'a, 'b) ReasonReact.component (defined as
    (string, string, 'a, 'a, 'b) ReasonReact.componentSpec)

The incompatible parts:
  ReasonReact.stateless (defined as unit)
  vs
  string
```

**Comment by rickyvetter** [comment]
Error messages have been improved and you can’t get this error with the new hooks api.
