### ISSUE TITLE
Website translation

### ISSUE THREAD

**Issue by flppv** [reasonml/reason-react#235]
Hey there!

I've started translation of the docs on crowdin into Russian language, and I found that some pages are not presented there, and they are placed in a repo under `website` directory. There is a `pages/en` folder. 

Can I translate them as well and push with PR? If so, should I duplicate folder into `pages/ru` ?

**Comment by chenglou** [comment]
Hey! You mean in https://crowdin.com/project/reason-react/ru#? Which page isn't there?

**Comment by flppv** [comment]
@chenglou I mean this page: https://reasonml.github.io/reason-react/ for example, docs navigation, an other pages that are not presented at Crowdin

**Comment by chenglou** [comment]
Ah, those are this file: https://crowdin.com/translate/reason-react/50/en-ru

Closing =). Thanks for the initiative!

**Comment by flppv** [comment]
If I take this string from index page for example it is not presented in en.json file

![image](https://user-images.githubusercontent.com/6984143/40881098-878a832a-66e0-11e8-9149-fbccbd6dd0d2.png)

But it is hardcoded in this file https://github.com/reasonml/reason-react/blob/master/website/pages/en/index.js (line 154)

**Comment by chenglou** [comment]
Ah you're right, I forgot to add translate tags to those. Fixed now. Thanks! Ping me if there's anything missing.

**Comment by flppv** [comment]
@chenglou so fast 🔥🔥🔥Thank you!
