### ISSUE TITLE
npm start and npm run webpack not starting application

### ISSUE THREAD

**Issue by harsh-vardhhan** [reasonml/reason-react#246]
I did **npm start** and **npm run webpack** and it shows no errors but the application doesn't start on localhost:3000. What am I doing wrong here ?

**Comment by thomasthiebaud** [comment]
For me it starts on `http://localhost:8080/`

**Comment by TrakBit** [comment]
@thomasthiebaud  no for me it's not running on 8080 either

**Comment by thangngoc89** [comment]
@TrakBit How did you create your project? What is your environment? How to reproduce this error?

**Comment by TrakBit** [comment]
@thangngoc89 Did exactly as mentioned in reason-react docs
```
npm install -g bs-platform
bsb -init my-react-app -theme react
cd my-react-app && npm install && npm start
# in another tab
npm run webpack
```
**Environment** - 
**OS** : Mac
**npm** : 5.6.0
**node** : 8.11.2

**Comment by thangngoc89** [comment]
This is a minimal boilerplate so there won't be any server for you, you just open the index.html file locally and start developing.
