### ISSUE TITLE
Add support for React context

### ISSUE THREAD

**Issue by maxdeviant** [reasonml/reason-react#25]
From the [ReasonReact docs](https://reasonml.github.io/reason-react/index.html#reason-react-miscellaneous):

>ReasonReact doesn’t support ReactJS context (yet).

What needs to take place in order for ReasonReact to support context? Are we waiting for the context API to become stable before adding in support for it?

**Comment by chenglou** [comment]
Yeah, waiting for that. Though it might take a while for it to be stable...

**Comment by maxdeviant** [comment]
@chenglou I suppose it's probably better to wait to implement context until it stabilizes. That way we can avoid some churn.

Whether or not that is a feasible plan really depends on where that sits on the React core team's priority list 😅

**Comment by aappddeevv** [comment]
You could allow the self record passed to the lifecycle methods to be extensible by component authors and create a mkSelf type method to allow it to be created. That way you could add anything you want to self and make it available in your component. This would require a change in the reasonreact but can be API neutral. It would make the api for people who want to change it for a specific component harder of course :-) It's also probably a good escape hatch that is consistent with how the self is created already.

**Comment by aappddeevv** [comment]
You could allow the self record passed to the lifecycle methods to be extensible by component authors and create a mkSelf type method to allow it to be created. That way you could add anything you want to self and make it available in your component. This would require a change in the reasonreact but can be API neutral. It would make the api for people who want to change it for a specific component harder of course :-) It's also probably a good escape hatch that is consistent with how the self is created already. I've done this for a scala.js version of reasonreact to pull in the context for exactly this reason.

**Comment by aappddeevv** [comment]
You could make the self record (passed to the API functions) extensible so that clients could enhance it for the components they care about it. I did that with my reasonreact-like bindings that I wrote in scala.js. You would then just need to write a `mkSelf` type function that can be supplied so that the proper self can be created. It could be an unsupported escape hatch.

**Comment by farism** [comment]
Now that the context API has been stabilized (https://github.com/facebook/react/pull/11818) and is going to land in React 16.3 any thoughts on this?

**Comment by kennetpostigo** [comment]
Might be a good time to add context support not that they've released the new API for it.

**Comment by CharlieGreenman** [comment]
I'm going to try and work on this binding. I have 4-5 hours from now until Thursday est. so no promises. Will report back, around then.

**Comment by CharlieGreenman** [comment]
Worked on this a tad tonight. Three things I need to do: 

1. Set up regular react environment and take context api for a spin
2. Fork repo and set up binding in the ReactDom.re file I am assuming(still have to figure this one out) 
3. Use forked repo in react-reason repo and see if working properly. 

Still working on 1.

**Comment by jumoel** [comment]
Any news on this? Any way I can be of assistance?

**Comment by jumoel** [comment]
Just saw this: https://github.com/reasonml/reason-react/pull/226

**Comment by phated** [comment]
This is now available in the `React` module as of 0.7.0 - see https://github.com/reasonml/reason-react/blob/master/src/React.re#L46
