### ISSUE TITLE
Implement React's Pointer Events

### ISSUE THREAD

**Issue by nickretallack** [reasonml/reason-react#256]
[React supports Pointer Events now.](https://reactjs.org/blog/2018/05/23/react-v-16-4.html)  It works in Chrome, Firefox, and IE/Edge.  You have to bring your own polyfill [for Safari](https://caniuse.com/#search=pointer) but [there are some mature ones](https://github.com/jquery/PEP).

Unfortunately, even if I include the polyfill, I can't just set `onPointerDown` events on my ReasonReact DOM elements as the type system considers it an error.  Could we change this?  And also add the custom attributes required by [PEP](https://github.com/jquery/PEP)?  Is there a way for me to extend what attributes are allowed on a DOM element in order to support this myself?  Should I be using cloneElement as an escape hatch?

**Comment by peterpme** [comment]
For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Please re-open if this is still relevant. Thanks!

**Comment by nickretallack** [comment]
I haven't checked recently.  Did this ever get implemented?

**Comment by peterpme** [comment]
Nope

**Comment by nickretallack** [comment]
Here's the PR I wrote 2 years ago attempting to add this to my local setup.  Ultimately I didn't use it though.

**Comment by nickretallack** [comment]
Ok, I'm working on a proper change, but...  it would be nice if ReactEvent.re(i) followed the inheritance structure for event types instead of just repeating their fields over and over.  Is that possible?  I'll ask on discord for help with this tomorrow.

**Comment by nickretallack** [comment]
The new PR: https://github.com/reasonml/reason-react/issues/256#issuecomment-630648149
