### ISSUE TITLE
`"autoFocus": ""` camel casing broke in cloneElement props

### ISSUE THREAD

**Issue by AdamBrodzinski** [reasonml/reason-react#258]
I'm working on a form library and I have the need to pass unsafe props down into an input with `cloneElement`. This works as expected except for the `"autoFocus"` attribute. If I use the camel cased version (the latest stable) Chrome does not auto focus on render. 

However, if I change it to `"autofocus"` then it does 🤔, but I get the warning:
```
Warning: Invalid DOM property `autofocus`. Did you mean `autoFocus`?
```
 I've checked other attributes like `"maxLength"`and those work fine camel cased.

**Sample code:** 
minimal repro (using bsb 4.0): [/AdamBrodzinski/reason-react-bug-repro](https://github.com/AdamBrodzinski/reason-react-bug-repro/blob/master/src/Index.re)

```javascript
let input = <input type_="text" name="foo" />;

/* does not work, no warning */
ReasonReact.cloneElement(input, ~props={"autoFocus": ""}, [||])

/* works, but has warning */
ReasonReact.cloneElement(input, ~props={"autofocus": ""}, [||])
```

**Expected Behavior:**
Input focuses on render

![screen shot 2018-07-11 at 10 42 53 am](https://user-images.githubusercontent.com/1445367/42583720-33d28964-84f7-11e8-83ba-0994f2f85d0b.png)

**Actual Behavior:**
Input *does not* focus on render

![screen shot 2018-07-11 at 10 43 47 am](https://user-images.githubusercontent.com/1445367/42583783-5076c4c2-84f7-11e8-8b5e-11556df29cd3.png)

**Versions:**
ReasonReact: 0.4.0
bsb: 4.0 (I have also have use 3.x with the same issue)
OS: OSX 10.12

**Comment by peterpme** [comment]
For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Please re-open if this is still relevant. Thanks!
