### ISSUE TITLE
Missing information in the Docs on typing children

### ISSUE THREAD

**Issue by aloifolia** [reasonml/reason-react#264]
If I want to type a property to receive a specific kind of react element, the docs currently do not explain whether that is possible. Sometimes parent components expect to receive certain elements as children in order to work properly. 

E.g. if you try to write bindings for js-lingui, you will find that the `Trans` component expects the children to either be strings or `Text` components: https://lingui.github.io/js-lingui/tutorials/react-native.html. So, as a beginner, you might be tempted to write bindings this way:

```ocaml
[@bs.module "@lingui/react"]
external checkbox : ReasonReact.reactClass = "Trans";

let make = (children: BsReactNative.Text) =>
  ReasonReact.wrapJsForReason(~reactClass=checkbox, children);
```

This is not possible since `Text` is a module, not a type.

It would be very useful to have this use case covered by the docs. If there is a good reason for why this feature cannot ever be implemented with ocaml/ReasonML, it would be nice to have the explanation in the docs, as well.

**Comment by peterpme** [comment]
For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Please re-open if this is still relevant. Thanks!
