### ISSUE TITLE
How to get state inside `self.onUnmount()`

### ISSUE THREAD

**Issue by thangngoc89** [reasonml/reason-react#266]
`self.onUnmount()` provides a really useful interface for preventing setState when component unmounted.

But sometimes, you need to access state inside `onUnmount`. Currently, there is no way to do that. Should I just move the logic to `willUnmount` when I need access to state on unmount? 

cc @chenglou  @rickyvetter

**Comment by flash-gordon** [comment]
@thangngoc89 you can use `handle` for this, can't you?
