### ISSUE TITLE
 Improve debugability of reason component props

### ISSUE THREAD

**Issue by barkmadley** [reasonml/reason-react#27]
Copied from https://github.com/chenglou/reason-react-example/issues/21 (wrong place)

---

Reading the ReasonReact.re module has been enlightening as to how to create type safe bindings to a fairly complex and dynamic javascript library. Definitely awesome work by the team to get this far (and make the interface extremely simple and flexible).

I have done an experiment with part of my companies code base that shows that Reason can be trivially integrated and used to provide type safety to our react components. As part of the feedback of this experiment, one of my colleagues asked how to debug a Reason components props?

While the bucklescript output is easy to add breakpoints to, there are also other tools that can help debug a react component, particularly in more complex scenarios. I am talking specifically about the React Developer Tools for Chrome specifically: https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi , but I am sure there are other tools that make use of the react library to provide other information that can help a user of react identify problem components.

I have attached some screenshots of how Reason components are rendered in the React Developer Tools for the snippet of Reason posted below, and as should be evident, the debugability of the FA component much lower than that of the LikeStatus component, primarily because the reason props are opaque to the rest of the system.

```reason
module FontAwesome = {
  let component = ReasonReact.statelessComponent "FA";
  let make name::name _children => {
    ...component,
    render: fun () _ => {
      <i className={"icon fa fa fa-" ^ name} />
    }
  };
};

let component = ReasonReact.statelessComponent "LikeStatus";
let make numLikes::numLikes ::isLiked ::canLike _children => {
  ...component,
  render: fun () _ => {
    ReactDOMRe.createElement "like-status" [|
      <span className="num-likes">{ReactRe.stringToElement (string_of_int n ^ " people like this")}</span>,
      if isLiked {
        <span className="unlike">
          <FontAwesome name="thumbs-up" />
          <span>{ReactRe.stringToElement "Unlike"}</span>
        </span>
      } else {
        /* !isLiked */
        if canLike {
          <span className="like">
            <FontAwesome name="thumbs-o-up" />
            <span>{ReactRe.stringToElement "Like"}</span>
          </span>
        } else {
          ReactRe.nullElement
        }
      }
    |]
  }
};

let comp =
  ReasonReact.wrapReasonForJs
    ::component
    (fun jsProps =>
      make
        numLikes::jsProps##numLikes
        isLiked::(Js.to_bool jsProps##isLiked)
        canLike::(Js.to_bool jsProps##canLike) [||]
    )
```

<img width="907" alt="screen shot 2017-06-23 at 12 00 22 pm" src="https://user-images.githubusercontent.com/143135/27463531-997d863e-580b-11e7-9c64-9c5c15917d1b.png">

I propose a `debugProps` feature in `componentSpec` where a component can return what it considers to be it's props as a Js object that is merged with the props next to "reasonProps" (specifically here: https://github.com/reasonml/reason-react/blob/402225ce200bf20fa6a16ae0d121dd25d589b232/src/reasonReact.re#L552 ),  It won't be as fool proof as the debugability of the rest of the react ecosystem, but it gives us a backdoor into inspecting the prop arguments that are given to our components make functions.

Let me know what you think.

**Comment by barkmadley** [comment]
https://twitter.com/jordwalke/status/880930246601527296 reminded me to check this issue was properly filed.

**Comment by chenglou** [comment]
Hey! The source code comment might be a little out of date btw. But thanks for reading through that. Since we're using labelled arguments we'll only be able to turn them into introspectable things through a ppx. Might be an easy ppx or a hard one.

**Comment by Anahkiasen** [comment]
Any news on this one?

**Comment by rickyvetter** [comment]
This has been addressed with JSX 3 and the new functional React components. Props are debuggable using standard React dev tools.
