### ISSUE TITLE
Add aria-current support

### ISSUE THREAD

**Issue by danben4** [reasonml/reason-react#274]
Right now the support for `aria-current` is commented out: https://github.com/reasonml/reason-react/blob/6de6b7723aa4402922bd8717c2098868afe8570a/src/ReactDOMRe.re#L97

Is there any specific reason for this? Is it possible to add support for this attribute?

**Comment by mikaello** [comment]
See my comment in https://github.com/reasonml/reason-react/issues/309#issuecomment-466050301 (the issue that is blocking `aria-*` is [[@bs.string] for bs.deriving abstract](https://github.com/BuckleScript/bucklescript/issues/2834) in the BuckleScript repo)

**Comment by davesnx** [comment]
Better late than never. Merged in #697.
