### ISSUE TITLE
Address deprecation of reducerComponentWithRetainedProps in documentation

### ISSUE THREAD

**Issue by sgny** [reasonml/reason-react#275]
Further to #248 

`reducerComponentWithRetainedProps` appears in an example on documentation in React lifecycles, but is apparently deprecated (verified with @thangngoc89 on Discord). For the obsolete example, refer to
https://github.com/reasonml/reason-react/blob/master/docs/lifecycles.md

I don't understand how I started to get the compiler error only yesterday and especially without updating `bs-platform` (already using 4.05 since its release) or `reason-react` (using commit e1783a22b80b36cc15af6dca0f54edbdc549c3fc from Aug 14) while I've been making use of several components defined as `reducerComponentWithRetainedProps` in my app in the past few months.

I dug into the source for BuckleScript and realized that the function is deprecated for versions of `reason-react` above 0.3.4, so for the moment I edited the version number and rebuilt `reason-react` to avoid having to change my components. According to the source code, it seems that the function is deprecated for a future version of reason-react where retainedProps is deprecated. However, without `getDerivedStateFromProps`, I don't think future has quite arrived.

As of now, there seems to be no method to keep track of props (if I'm mistaken please advise and I'll help update documentation with an example) and trigger function calls when a given prop changes. Without such functionality, one cannot create reusable blackbox components with animation based on changes to some prop and have to resort to managing such animations from the parent component.

**Comment by bloodyowl** [comment]
the usual way to do that right now is to do the following:

```reason
type state = {retained: int};

let component = ReasonReact.reducerComponent("Comp");

let make = (~prop: int, _) => {
  ...component,
  /* ... */
  willReceiveProps: ({state}) => state.retained !== props : {retained: prop} : state,
 /* ... */ 
}
```

**Comment by sgny** [comment]
Thanks, I'll prepare a PR to update the documentation.

**Comment by peterpme** [comment]
For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Please re-open if this is still relevant. Thanks!
