### ISSUE TITLE
npm run webpack failed

### ISSUE THREAD

**Issue by geohuz** [reasonml/reason-react#279]
Just followed the instruction on the installation page, however I got the following error when running "npm run webpack":

`
./node_modules/webpack-cli/bin/config-yargs.js:89
describe: optionsSchema.definitions.output.properties.path.description,
^

TypeError: Cannot read property 'properties' of undefined
...

**Comment by geohuz** [comment]
migrating to latest webpack solved the error for me: webpack-cli@3.1.1

**Comment by WishCow** [comment]
Ran into this as well, installing webpack-cli@3.1.1 solved it.

Ping @chenglou @zploskey, should this be in the installation page?

**Comment by zploskey** [comment]
I suspect that BuckleScript will need to ship an update to the react template with an updated webpack-cli version in its next release. Likely a webpack-cli update in the 2.x series broke something.
