### ISSUE TITLE
Clearing forms; something that seemed trivial 

### ISSUE THREAD

**Issue by DavidWhit** [reasonml/reason-react#282]
Alright, coming from react and some functional programming and I've been about an 2 hours in so prob just me...
I did come across this little gem after some hunting for synthetic events 
_event->ReactEvent.Form.target##value

Ok... but lets say I'd want to have a clear button to remove the values state of course doesn't change and input field for a current form something like
document.querySelectorAll("#aformid").forEach( (n,i) => n[i].value = null ) 

Now if I call a handler and then use %bs.raw the function gets called ahead of time before it's actually clicked where as in react it doesn't via the handler. Though in react it wouldn't get called by the handler until it's actually already rendered to the dom.

 So is there an idiomatic Reason way to handle such things...?

**Comment by sgny** [comment]
> Ok... but lets say I'd want to have a clear button to remove the values state of course doesn't change

You should indeed update the state when the button is clicked. Define a new action, and in the reducer set the state field to e.g. an empty string to reset the field.

For the input field to reflect your input, you have to update the state any way, for more information refer to  [this tutorial](https://jaredforsyth.com/posts/a-reason-react-tutorial/) by Jared Forsyth.

**Comment by DavidWhit** [comment]
Oh right... forgot about setting the value on the input to state was thinking about the context I was in and completely  missed the mark. That link helped as well.
