### ISSUE TITLE
Installation fails: inconsistent assumptions over interface Pervasives

### ISSUE THREAD

**Issue by vog** [reasonml/reason-react#289]
I'm trying to get started with the provided commands in the manual:

* https://reasonml.github.io/reason-react/docs/en/installation

That is:

```shell
npm install -g bs-platform
bsb -init my-react-app -theme react
cd my-react-app && npm install && npm start
# in another tab
npm run webpack
```

Using this vanilla setup, it fails without modification right at `npm start`:

```
> bsb -make-world -w

[18/18] Building src/ReactDOMRe.mlast.d
[9/9] Building src/ReactDOMRe.cmj
>>>> Start compiling
[1/3] Building src/Component1-ReactTemplate.cmj

  We've found a bug for you!
  /.../my-react-app/src/Component1.re
  
  It's possible that your build is stale.
  Try to clean the artifacts and build again?
  
  Here's the original error message
  The files /.../my-react-app/node_modules/bs-platform/lib/ocaml/pervasives.cmi
  and /.../node_modules/reason-react/lib/ocaml/ReasonReact.cmi
  make inconsistent assumptions over interface Pervasives
  
[2/3] Building src/Component2-ReactTemplate.cmj

  We've found a bug for you!
  /.../my-react-app/src/Component2.re
  
  It's possible that your build is stale.
  Try to clean the artifacts and build again?
  
  Here's the original error message
  The files /.../my-react-app/node_modules/bs-platform/lib/ocaml/pervasives.cmi
  and /.../node_modules/reason-react/lib/ocaml/ReasonReact.cmi
  make inconsistent assumptions over interface Pervasives
  
>>>> Finish compiling(exit: 1)
```

**Comment by superhawk610** [comment]
What system are you running on? I wasn't able to replicate this on Ubuntu 18.04.

Paste the output of this from within your `my-react-app` directory so I can verify your install location/versions:
```
npm ls bs-platform reason-react
```

**Comment by Blackth0rn** [comment]
I also had the same issue with bs-platform 2.2.3, upgrading to bs-platform 4.0.7 has fixed the issue.

**Comment by phated** [comment]
Usually this means you require a `bsb -clean-world` to remove old files that were compiled with a different compiler version or something. There was also an issue in the past where the global bs-platform could error with this but I believe it is solved now.

**Comment by rickyvetter** [comment]
For a few versions ReasonReact was shipping some of unnecessary BS artifacts inadvertently. This required a clean build to resolve. I believe this is no longer an issue in the most recent release, if you run into it again then please re-open but know that you can use -clean-world as a workaround.
