### ISSUE TITLE
Unable to make a keyed fragment with JSX

### ISSUE THREAD

**Issue by MoOx** [reasonml/reason-react#293]
I am trying to use a keyed fragment, [something you can do with reactjs](
https://reactjs.org/docs/fragments.html#keyed-fragments).

I tried this

```re
<ReasonReact.fragment key={"key"}> child </ReasonReact.fragment>
```

But I am getting 

```console
  We've found a bug for you!
  /Users/moox/Sync/Development/dame.bio/src/components/Comments.re 80:15-35

  78 ┆ ->Belt.List.mapWithIndex((index, comment) => {
  79 ┆     let isOwner = comment.author == 2;
  80 ┆     <ReasonReact.fragment key={string_of_int(comment.id)} >
  81 ┆       {index > 0 && comment.parent == 0 ? <Spacer /> : nothing}
  82 ┆       <View style=styles##comment>

  The module or file ReasonReact.fragment can't be found.
  - If it's a third-party dependency:
    - Did you list it in bsconfig.json?
    - Did you run `bsb` instead of `bsb -make-world`
      (latter builds third-parties)?
  - Did you include the file's directory in bsconfig.json?

>>>> Finish compiling(exit: 1)
```

Not that my IDE can resolve it (and I see it in the source too).

<img width="802" alt="screenshot 2018-11-01 at 20 48 07" src="https://user-images.githubusercontent.com/157534/47875913-194f2a00-de18-11e8-8a1f-ea67ce5cd4df.png">

What am I missing with JSX?

---

Just in case, I am using reason-react 0.5.3 and `<> </>` works.

**Comment by maarekj** [comment]
Reason-react.fragment seems to be a value not a module.
Jsx accepts only module which contains a make function

**Comment by MoOx** [comment]
@maarekj Just did a PR to add support for it :) 
https://github.com/reasonml/reason-react/pull/295

**Comment by phated** [comment]
@MoOx a `Fragment` component now exists in the `React` module!  https://github.com/reasonml/reason-react/blob/master/src/React.re#L77
