### ISSUE TITLE
Are both yarn.lock and package-lock.json necessary?

### ISSUE THREAD

**Issue by MoOx** [reasonml/reason-react#294]
Hi. Just curious here about the motivation of having 2 lock files.
It seems not to be a good idea for contributors (as this can be a pain to have to update both lock files whenever something change in package.json).
Maybe the team should choose one and stick to it?

**Comment by jchavarri** [comment]
`package-lock` was removed in https://github.com/reasonml/reason-react/commit/2971a44ae27046edf5a17cd83bbdb62dc940811c#diff-32607347f8126e6534ebc7ebaec4853d so I think this can be closed? cc @rickyvetter

**Comment by MoOx** [comment]
Perfect!
