### ISSUE TITLE
Support for React 16.6 and 16.7 new API (?)

### ISSUE THREAD

**Issue by gaku-sei** [reasonml/reason-react#299]
I was wondering, with all the fuss around the new Hook API (that actually looks promising), if React Reason had any plan to implement it (even if it's still _super_ experimental).

It feels like Reason React would benefit from the new `useContext` or `memo` functions. The former one lowering the amount of props going from the parent to the children, while the second one could improve the performances.

I perfectly understand it could be challenging (type wise), and maybe it does not match Reason React's philosophy. I just wanted to know if this new API, or something similar, was planned in the future.

**Comment by jihchi** [comment]
I would like to add some information for someone who could be interested to try those experimental API:
##  [SimpleReasonReact](https://github.com/eldh/simple-reason-react)
> [SimpleReasonReact](https://github.com/eldh/simple-reason-react) is a fork of [ReasonReact](https://reasonml.github.io/reason-react) adapted to work with Hooks, with Hooks types from [Jared Forsyth](https://github.com/jaredly/hooks-experimental).



## [hooks-experimental](https://github.com/jaredly/hooks-experimental)
> An experiment using react's new "hooks" with ReasonReact
> **WARNING**: Do not use for anything real.

**Comment by Voronar** [comment]
Any progress with new API?

**Comment by oddlyfunctional** [comment]
React finally had a [stable release](https://reactjs.org/blog/2019/02/06/react-v16.8.0.html) with the Hooks API, maybe now we'll have some news? 😃

**Comment by eldh** [comment]
There's been talk on Discord about a new release coming this month. Guessing it will be alpha/beta stage at first but we'll see. (I'm sure the maintainers will chime in when they have something substantial to share.)

**Comment by gaku-sei** [comment]
Great news! There is a `hooks` branch on this exact repo: https://github.com/reasonml/reason-react/tree/hooks. So far the Provider, and some hooks, have been implemented!

**Comment by MoOx** [comment]
Merged into master!
