### ISSUE TITLE
Less Boilerplate Code for Interop with existing JavaScript Components

### ISSUE THREAD

**Issue by shybyte** [reasonml/reason-react#30]
The current document way to use existing JavaScript components (https://github.com/chenglou/reason-react-example/blob/master/src/interop/myBannerRe.re) needs a lot of boilerplate code when you have long lists of props and lots of components.

I wonder if there is a more concise way using a mechanism similar to the external props in https://github.com/reasonml/reason-react/blob/master/src/reactDOMRe.re#L58.

**Comment by cies** [comment]
Repo moved, updated link: https://github.com/reasonml-community/reason-react-example/blob/master/src/interop/MyBannerRe.re

**Comment by phated** [comment]
The new zero-cost bindings have removed all this boilerplate.

It now looks like:
```reason
[@bs.module "./path/to/Component.js"][@react.component]
external make: (~name: string) => React.element = "default";
```

Docs available at https://reasonml.github.io/reason-react/docs/en/components#interop
