### ISSUE TITLE
Comments require space after JSX elements

### ISSUE THREAD

**Issue by jdeisenberg** [reasonml/reason-react#300]
Create a project and install:
```
bsb -init commentbug -theme react
cd commentbug
npm install
```
Edit file `Component1.re` on line 20 to read as follows, with the comment’s opening `/` immediately following the `>`:
```
<div onClick=(self.handle(handleClick))>/* comment */
```
Now compile with `bsb -make-world`:
```
File "/home/username/commentbug/src/Component1.re", line 20, characters 43-44:
Error: 3764: <syntax error>
```
Go back to `Component1.re` and add a space after the closing `>`, and re-compile -- everything works great.

**Comment by anmonteiro** [comment]
This should go in the Reason repo.

**Comment by jdeisenberg** [comment]
Sorry; will copy it there.
