### ISSUE TITLE
Add autoCapitalize prop to match React's iOS specific input attribute

### ISSUE THREAD

**Issue by wegry** [reasonml/reason-react#303]
React supports a couple iOS specific input props. It'd be nice to have access to [autoCapitalize.](https://github.com/facebook/react/blob/b59fb796ea2c05c8609858fc28b707d13245fd9c/docs/docs/reference-dom-elements.md#all-supported-html-attributes)

**Comment by peterpme** [comment]
Merged. Thanks!
