### ISSUE TITLE
Breaks in specific cases when using aggressive code minification 

### ISSUE THREAD

**Issue by baldurh** [reasonml/reason-react#306]
_More of an observation than a bug report:_

I’m rendering `reason-react` components inside storybook and production builds of storybook use `babel-preset-minify` which in turn uses `babel-plugin-minify-dead-code-elimination` which removes unused function arguments.

I have a reducer component which has a very simple state. The reducer method always returns a new state without spreading the old state and so the `state` argument is unused.
![image](https://user-images.githubusercontent.com/1823617/49614197-743ce980-f9a1-11e8-9e77-35b0d52ce679.png)

When this code is run through storybook’s webpack setup it removes the unused `state` argument from the code.

This leads to an exception on [this line](https://github.com/reasonml/reason-react/blob/master/lib/js/src/ReasonReact.js#L267) (inside the curry). Because the reducer method has only one argument [this line] has already called the method with the one argument and so the curry returns the state and not a partially applied function.

`bs.js` file
<img width="375" alt="wowair_tabs_bs_js_ _monorepo" src="https://user-images.githubusercontent.com/1823617/49614754-26c17c00-f9a3-11e8-923e-ffbd1570664b.png">

Minified code in the browser
<img width="699" alt="storybook" src="https://user-images.githubusercontent.com/1823617/49614610-b0bd1500-f9a2-11e8-8c55-aecdeeb92c61.png">

<img width="668" alt="storybook" src="https://user-images.githubusercontent.com/1823617/49614666-d77b4b80-f9a2-11e8-932d-e1a0d5220c82.png">

I hope this is helpful to someone, it took me all day to figure this out 🙈

**Comment by rickyvetter** [comment]
Thanks for reporting this and sorry for the complete lack of response. Looking through old issues now and saw this. Definitely something we could flag from the BuckleScript side - specifically seems to be an issue with `babel-plugin-minify-dead-code-elimination` when `keepFnArgs` is false. This will definitely not play well with BuckleScript generated code. cc @bobzhang
