### ISSUE TITLE
Example fails to build from a path containing a parenthesis

### ISSUE THREAD

**Issue by cician** [reasonml/reason-react#315]
Hi, I wanted to try ReasonReact, but the example failed to build for me at first try with this error:
```
npm install && npm start
...
> my-react-app@0.1.0 start /tmp/New Folder (3)/my-react-app
> bsb -make-world -w

[18/18] Building src/ReactDOMRe.mlast.d
[9/9] Building src/ReactDOMRe.cmj
>>>> Start compiling 
[7/7] Building src/Component2.mlast.d
[1/3] Building src/Component1-ReactTemplate.cmj
/bin/sh: 1: Syntax error: "(" unexpected
[2/3] Building src/Component2-ReactTemplate.cmj
/bin/sh: 1: Syntax error: "(" unexpected
>>>> Finish compiling(exit: 1)
```

I followed the instructions from here: https://reasonml.github.io/reason-react/docs/en/installation. After some guesswork I got it to work by renaming the directory to /tmp/NewFolder3.

Note that I can compile the basic-reason "theme" without problems with both yarn and npm even if the directory contains parentheses. Both projects use bs-platform 4.0.18. I'm on Linux (an Ubuntu 18.04 derivate). It seems like just having reason-react dependency in the bsconfig.json is enough to trigger the problem.

**Comment by peterpme** [comment]
For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Please re-open if this is still relevant. Thanks!
