### ISSUE TITLE
Router only replaces last 'directory' of path when no basepath is set

### ISSUE THREAD

**Issue by SSoelvsten** [reasonml/reason-react#342]
I set up the router following the [documentation](https://reasonml.github.io/reason-react/docs/en/router.html), The project was set up using the Reason React template of the CLI, which supplies you with an `index.html` file with the following header.

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>ReasonReact Examples</title>
  </head>
   ...
</html>
```
If a `<base href="/" />` is not set, then the React Router does not at all behave as expected, where only the last directory of the path is set. Pushing urls like `entity/id` and `frontpage` to the router would then result in the following undesired behaviour
```
push: "frontpage"     => url: /frontpage
push: "entity/1"      => url: /entity/1
push: "frontpage"     => url: /entity/frontpage
push: "entity/2"      => url: /entity/entity/2
```
I don't know if adding `<base href="/" />` is undesired, if it is missing in the template or a note is missing in the documentation.

**Comment by bloodyowl** [comment]
I believe this is the expected behaviour, it works just like regular links do.

**Comment by bloodyowl** [comment]
if you want links to be absolute, you can prefix the link with `/`.

**Comment by SSoelvsten** [comment]
I also found it weird if something that basic should have been an implementation issue. I apparently am missing knowledge in how to use links. xD
