### ISSUE TITLE
ReactDOMRe & ReactDOMServerRe not adapted for React (hooks)

### ISSUE THREAD

**Issue by MoOx** [reasonml/reason-react#360]
They reference ReasonReact.reactElement.

@rickyvetter open for a PR that add `ReactDOM` & `ReactDOMServer` that are basically the same with `React.element` etc?

**Comment by rickyvetter** [comment]
Just in case you didn’t notice, `ReasonReact.reactElement` is just an alias for `React.element`. I’d be fine with a PR that makes those changes to `ReactDOMRe` (and all others). Adding a new module is a bigger change. I don’t want to make that until we are confident with the api. See @bordoley’s comments on the initial hooks PR for some context but I don’t think ReactDOM’s api is set in stone and I want to save this new module for that (very minor) breaking change.
