### ISSUE TITLE
JSX 3 ppx regression with auto scope/open (?)

### ISSUE THREAD

**Issue by MoOx** [reasonml/reason-react#362]
Sorry about the title, I am totally unsure about how to fill it :) Feel free to rename.

---

With jsx 2 I had a component exporting a variant type that I was easily refering inside as a component props

<details>
<summary>Component code</summary>

```re
open BsReactNative;

let component = ReasonReact.statelessComponent("Spacer");

let space = 20.;

type size =
  | XXL
  | XL
  | L
  | M
  | S
  | XS
  | XXS
  | Custom(float)
  | None;

let make =
    (
      ~vertical=None,
      ~horizontal=None,
      ~style=Style.style([]),
      ~pointerEvents=`auto,
      children,
    ) => {
  ...component,
  render: _self =>
    <View
      style={Style.concat([
        Style.style(
          switch (vertical) {
          | XXL => [Style.paddingVertical(Pt(space *. 4.))]
          | XL => [Style.paddingVertical(Pt(space *. 3.))]
          | L => [Style.paddingVertical(Pt(space *. 2.))]
          | M => [Style.paddingVertical(Pt(space *. 1.))]
          | S => [Style.paddingVertical(Pt(space *. 3. /. 4.))]
          | XS => [Style.paddingVertical(Pt(space *. 2. /. 4.))]
          | XXS => [Style.paddingVertical(Pt(space *. 1. /. 4.))]
          | Custom(value) => [Style.paddingVertical(Pt(value))]
          | None => []
          },
        ),
        Style.style(
          switch (horizontal) {
          | XXL => [Style.paddingHorizontal(Pt(space *. 4.))]
          | XL => [Style.paddingHorizontal(Pt(space *. 3.))]
          | L => [Style.paddingHorizontal(Pt(space *. 2.))]
          | M => [Style.paddingHorizontal(Pt(space *. 1.))]
          | S => [Style.paddingHorizontal(Pt(space *. 3. /. 4.))]
          | XS => [Style.paddingHorizontal(Pt(space *. 2. /. 4.))]
          | XXS => [Style.paddingHorizontal(Pt(space *. 1. /. 4.))]
          | Custom(value) => [Style.paddingHorizontal(Pt(value))]
          | None => []
          },
        ),
        style,
      ])}
      pointerEvents>
      ...children
    </View>,
};
```

</details>

And I was able to call

```re
<SpacedView vertical=XL />
```

XL was automatically available without having to explicitly tell the origin.
**Very convenient.**

I recently tried to use JSX 3 ppx and converted my component (but the type is just the same

<details>
<summary>Component code</summary>

```re 
[@bs.config {jsx: 3}];
open ReactNative;

let space = 20.;

type size =
  | XXL
  | XL
  | L
  | M
  | S
  | XS
  | XXS
  | Custom(float)
  | None;

[@react.component]
let make =
    (
      ~vertical=M,
      ~horizontal=M,
      ~style as s=?,
      ~pointerEvents=`auto,
      ~children,
    ) =>
  <View
    style=Style.(
      arrayOption([|
        switch (vertical) {
        | XXL => Some(style(~paddingVertical=Size.pt(space *. 4.), ()))
        | XL => Some(style(~paddingVertical=Size.pt(space *. 3.), ()))
        | L => Some(style(~paddingVertical=Size.pt(space *. 2.), ()))
        | M => Some(style(~paddingVertical=Size.pt(space *. 1.), ()))
        | S => Some(style(~paddingVertical=Size.pt(space *. 3. /. 4.), ()))
        | XS => Some(style(~paddingVertical=Size.pt(space *. 2. /. 4.), ()))
        | XXS =>
          Some(style(~paddingVertical=Size.pt(space *. 1. /. 4.), ()))
        | Custom(value) => Some(style(~paddingVertical=Size.pt(value), ()))
        | None => None
        },
        switch (horizontal) {
        | XXL => Some(style(~paddingHorizontal=Size.pt(space *. 4.), ()))
        | XL => Some(style(~paddingHorizontal=Size.pt(space *. 3.), ()))
        | L => Some(style(~paddingHorizontal=Size.pt(space *. 2.), ()))
        | M => Some(style(~paddingHorizontal=Size.pt(space *. 1.), ()))
        | S =>
          Some(style(~paddingHorizontal=Size.pt(space *. 3. /. 4.), ()))
        | XS =>
          Some(style(~paddingHorizontal=Size.pt(space *. 2. /. 4.), ()))
        | XXS =>
          Some(style(~paddingHorizontal=Size.pt(space *. 1. /. 4.), ()))
        | Custom(value) =>
          Some(style(~paddingHorizontal=Size.pt(value), ()))
        | None => None
        },
        s,
      |])
    )
    pointerEvents>
    ...children
  </View>;
```

</details>

But now I cannot do the call like I did and I have to do

```re
<SpacedView vertical=SpacedView.XL />
```

Looks like something is lost with the new ppx. Previous way was really convenient in tons of places, at least for me.
Can we adjust the generated code by the ppx to improve the situation with jsx 3 ?

**Comment by wegry** [comment]
I think this goes along with auto scope, but it looks like optional props in JSX 2 are mandatory in JSX 3.

**Comment by rickyvetter** [comment]
So JSX 3 has an extra layer of indirection for props which is that it uses `React.createElement` properly. Essentially the difference between `Foo.make(~bar, ~baz)` and `React.createElement(Foo.make, Foo.makeProps(~bar, ~baz))`. `Foo.makeProps` is generated as part of the ppx and so it needs to rely on the syntax to be generated. If it doesn't have a type that it can use from the syntax it uses a type argument (knowing that the type checker will catch the return value when it is passed to make). So I believe you can work around this by annotating your types (`~vertical:size=M,`). We could change this by generating a local open around the `makeProps` call - I am concerned about if that might ever be the thing you might not want. Specifically if you have types/values with the same name between files you could get very strange errors when using JSX to create components.

@wegry 
> it looks like optional props in JSX 2 are mandatory in JSX 3

How do you mean? You can add optional args in JSX 3 and they are not required to be passed by callers.

**Comment by wegry** [comment]
> How do you mean? You can add optional args in JSX 3 and they are not required to be passed by callers.

With bs-platform@6.0.1-dev and https://github.com/reasonml/reason-react.git#c368ef890dc56bc4006cd260aa85de4270a46df4 there was something going on with optional params. 

<img width="409" alt="Screen Shot 2019-04-10 at 4 03 36 PM" src="https://user-images.githubusercontent.com/5156873/55885585-81b1ec80-5baa-11e9-8108-05f20ba9fc5b.png">

This is part of a larger diff where jumping on bs-platform@0.7 and reason-react@0.7 got things back to where they were for optional params before. Button was defined as 

```reason
[@react.component]
let make =
    (
      ~label: t,
      ~onClick,
      ~size=`medium,
      ~version=`default,
      ~isOnColor=false,
      ~textColor=None,
      ~disabled=false,
      ~extraClasses="",
    )
```

**Comment by alexfedoseev** [comment]
> So I believe you can work around this by annotating your types (~vertical:size=M,).

Phew! Good thing I usually do this in abstractions 😃

**Comment by peterpme** [comment]
For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Please re-open if this is still relevant. Thanks!
