### ISSUE TITLE
JSX 3 and optional args

### ISSUE THREAD

**Issue by alexfedoseev** [reasonml/reason-react#369]
PPX crashes on optional args: https://cl.ly/d351b2ba8d26

Repro:

```reason
[@bs.config {jsx: 3}];

[@react.component]
let make = (~prop: string="") => React.null;
```

**Comment by wegry** [comment]
@alexfedoseev are you using bs-platform@5.0.0 or 5.0.1?

**Comment by alexfedoseev** [comment]
@wegry `5.0.1`

**Comment by Schmavery** [comment]
Also experiencing this on bs-platform 5.0.1. As a workaround(?)/contrasting example, it seems to be fine when I make the type definition an option:
```reason
[@bs.config {jsx: 3}];

[@react.component]
let make = (~prop: option(string)="") => React.null;
```

**Comment by alexfedoseev** [comment]
I updated to `5.0.2` but error is still there.
@Schmavery workaround works for me. Removal of annotation also works btw.

/cc @rickyvetter

**Comment by alexfedoseev** [comment]
Something very sketchy is going on here: https://cl.ly/1853f93ef764

**Comment by phated** [comment]
@alexfedoseev it's possible that the desugared version isn't using `~id?` syntax.

**Comment by alexfedoseev** [comment]
I also noticed that:

```reason
~prop: option(string)=?
```

became

```reason
~prop: string=?
```

The former is acceptable but requires explicitly passed `None` on a call site.

**Comment by alexfedoseev** [comment]
Although @Schmavery workaround compiles, it doesn't do what original annotation does: `option(type)` means value must be explicitly passed on a call site, unfortunately.

**Comment by rickyvetter** [comment]
Hey folks - can you try the ppx branch? Just pushed a change which seems to work with your cases but I want to make sure it handles the more complex cases in your app.

**Comment by wegry** [comment]
Barring doing additional work besides yarn add https://github.com/reasonml/reason-react\#ppx and doing a rebuild, it looks like the new ppx works for my medium sized Reason React app.

**Comment by alexfedoseev** [comment]
@rickyvetter I'm trying ppx branch and it still doesn't compile but now with error from compiler:

```reason
~color: Color.t=General
```

^ this triggers the following error:

```
Error: This variant pattern is expected to have type Color.t
       The constructor Some does not belong to type Color.t
```

if I change type to `~color: option(Color.t)=General` it compiles but now on the call site it must be either

```reason
<Link color=Some(General) />
// or
<Link color=None />
```

but I expect it to be either

```reason
<Link color=General />
// or
<Link />
```

**Comment by rickyvetter** [comment]
https://github.com/BuckleScript/bucklescript/pull/3493
