### ISSUE TITLE
[@react.component] and argument destructuring

### ISSUE THREAD

**Issue by alexfedoseev** [reasonml/reason-react#378]
It prolly impossible to handle this via ppx but just FYI:

```reason
[@react.component]
let make = (~tuple as (a, b)) => {
  // a & b are unbound here
};
```

**Comment by rickyvetter** [comment]
This is possible to handle. Will look into it but low pri compared to the optional and bs.module issues.

**Comment by alexfedoseev** [comment]
For sure.

**Comment by rickyvetter** [comment]
Heads up - this should be fixed in #ppx. Will be upstreaming to bs soon!

**Comment by rickyvetter** [comment]
https://github.com/BuckleScript/bucklescript/pull/3493
