### ISSUE TITLE
Renaming prop when binding to js component

### ISSUE THREAD

**Issue by alexfedoseev** [reasonml/reason-react#379]
Is it possible to rename prop when binding to js component? it doesn't seem that `bs.obj` allows that or I don't know how to use `bs.as` with it.

**Comment by rickyvetter** [comment]
No because bs.obj doesn’t support bs.as. You can do this yourself by dropping out of ppx and using bs.deriving abstract. There is an issue on the bs repo to support and if so we will be sure to support as well!

**Comment by alexfedoseev** [comment]
Thanks!
