### ISSUE TITLE
Prepare support for didCatch when released

### ISSUE THREAD

**Issue by bloodyowl** [reasonml/reason-react#38]
https://github.com/facebook/react/pull/10200

**Comment by bsommardahl** [comment]
I find myself needing `didCatch` right now. Where does this fall on the roadmap?

**Comment by bloodyowl** [comment]
I can put up a PR if implementing it if looks ok to @chenglou & @rickyvetter

**Comment by Haroenv** [comment]
Would also be up for a PR if this is a feature we want

**Comment by bloodyowl** [comment]
should the signature be something like `didCatch: ('self, 'error, 'info) => unit`?

cc @rickyvetter

**Comment by rickyvetter** [comment]
Yeah that looks good! Should make things more concrete where possible.

`info` seems to have a pretty defined shape:
https://github.com/facebook/react/blob/55787006710bd8ef89a01d60c4a9cfa58c71035d/packages/react-reconciler/src/ReactFiberUnwindWork.js#L122-L124
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2223-L2228

I'm assuming error is a Js.Exn.t - but if it makes sense we could have our own type too.

**Comment by bloodyowl** [comment]
PR sent https://github.com/reasonml/reason-react/pull/247

**Comment by peterpme** [comment]
For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Please re-open if this is still relevant. Thanks!
