### ISSUE TITLE
v0.7.0: useEffect1 takes array as second argument, not plain value?

### ISSUE THREAD

**Issue by af** [reasonml/reason-react#384]
From the source:

```
external useEffect1:
  ([@bs.uncurry] (unit => option(unit => unit)), array('a)) => unit =
  "useEffect";
[@bs.module "react"]
external useEffect2:
  ([@bs.uncurry] (unit => option(unit => unit)), ('a, 'b)) => unit =
  "useEffect";
[@bs.module "react"]
external useEffect3: (unit => option(unit => unit), ('a, 'b, 'c)) => unit =
  "useEffect";
[@bs.module "react"]
external useEffect4: (unit => option(unit => unit), ('a, 'b, 'c, 'd)) => unit =
  "useEffect";
[@bs.module "react"]
external useEffect5:
  (unit => option(unit => unit), ('a, 'b, 'c, 'd, 'e)) => unit =
  "useEffect";
```

It was confusing to me that all of these functions take tuples as a 2nd argument, but `useEffect1` takes a (presumably 1-element) array instead of just the value `'a`. I'm guessing this is to ensure a JS array is always passed in the `useEffect` call on the JS side, but is this at least worth calling out in the docs? Seems like a potential footgun.

**Comment by wegry** [comment]
@af It's not necessarily a single element as the argument in useEffect1.

For example
```reason
let useOnMount = func => {
  React.useEffect1(
    func,
    // https://stackoverflow.com/a/53121021/1924257
    [||],
  );
};
```
When the component is mounted, this effect will only run once.

So long as the array is of the same type, and that type is able to check if equality is matched, then it doesn't matter as far as vanilla React is concerned. The binding is of an almost zero cost (besides the equality footgun).

[The React docs](https://reactjs.org/docs/hooks-effect.html#tip-optimizing-performance-by-skipping-effects) have more context.

**Comment by rickyvetter** [comment]
Agreed! Will add to docs.

**Comment by af** [comment]
Thanks @wegry, I didn't think of the "componentDidMount" empty-array case.

Seems to me since there is a version of the API that takes an array already, `useEffect{1,2,3,4,5}` could be collapsed into one `useEffectWithDeps(func, depsArray)` to simplify the API surface a bit. Maybe there's a benefit to having multiple tuple-based versions that I'm not seeing, though.

**Comment by wegry** [comment]
@af here's an example of where just using an array breaks down type-wise.

```reason
React.useEffect3(
  () =>
    if (!isDisabled && isFocused) {
      let arrowAround = e =>
        switch (e##key) {
        // ...Stuff
        };

      Document.addEventListener(`keydown, arrowAround);

      Some(() => Document.removeEventListener(`keydown, arrowAround));
    } else {
      None;
    },
  (isDisabled, isFocused, selected),    // Our sample deps array.
);
```

Two of the dependencies here are booleans (`isDisabled` and `isFocused`). `selected` is an int though. As far as the runtime is concerned, the tuple is compiled to a JS array, which React accepts without complaint.

If you were to say, wrap each item in a variant so you could have only `useEffect` and `useEffect1`, you have the problem that [bucklescript compiles variants to be array wrappers](https://reasonml.github.io/en/try?rrjsx=true&reason=C4TwDgpgBMULxQFBSgHygJQgQwDa5GTSgDkB7SACgGdgAnASwDsBzASiPQGUJGyBXagUrNgbANyJEAKWoA6XGRYBmSljwEANKQoRKAImr622nn0HDlbCUA). Depending on how often the runtime ends up constructing new variant instances, shallow equality won't work either.

**Comment by af** [comment]
Ah of course, heterogenous dependency types won't work within a single array, makes sense. Thank you for explaining!

**Comment by peterpme** [comment]
For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Please re-open if this is still relevant. Thanks!
