### ISSUE TITLE
Would you be open to add React.list?

### ISSUE THREAD

**Issue by nikgraf** [reasonml/reason-react#385]
Most of the times I use lists instead of arrays. This results in me doing this snippet over and over again:

```
->Belt.List.toArray
->React.array
```

In addition this causes confusion in beginner workshops (because I mostly use lists in the examples).

Would recommend to focus on using Arrays in these workshops or would you be open to add `React.list` that does the conversion internally?

**Comment by rickyvetter** [comment]
Not as titled no. We want React.re to be guaranteed 0 runtime and matching the api of React as close as possible. string and array are unfortunate necessities.
that said, i think this is what I would eventually like to exist in the ReasonReact namespace - things that are Reason specific that work well with React.

Before we do that I'd love to get more opinions about how other folks feel about this. Are there more utilities/interesting cases that could exist in thie ReasonReact/ReactUtils space?

**Comment by nikgraf** [comment]
Makes a lot of sense with the zero cost philosophy in mind. Thanks for the clarification!

**Comment by jaredly** [comment]
ReasonReact.list is very much needed 😅

**Comment by tcoopman** [comment]
I wonder if there are any benchmarks on the overhead of lists vs arrays (and the translation between them) for things that matter for Reason React? (Did a search but couldn't find anything)
