### ISSUE TITLE
Npm version not compatible with official

### ISSUE THREAD

**Issue by kamilkuz** [reasonml/reason-react#390]
I noticed that officialy version 0.7.0 was released but npm still shows 0.6.0. Is this for purpose or it's mistake ?

**Comment by MoOx** [comment]
It's tagged as beta on npm. You can try

```console
npm install reason-react@beta
```

Or directly

```console
npm install reason-react@0.7.0
```

Maybe they are waiting a little to consider this release stable :)

**Comment by kamilkuz** [comment]
I just specified 0.7.0 version in package.json - it's not problem for me. But in official blog (https://reasonml.github.io/reason-react/blog/2019/04/10/react-hooks) and in official documentation there is no information that this is beta version. I think its can be very confusing for many users.

**Comment by MoOx** [comment]
0.7.0 is now the latest on npm 🥳
