### ISSUE TITLE
Error: theme react-hooks not found

### ISSUE THREAD

**Issue by vgrafe** [reasonml/reason-react#398]
I hope this is the right place to ask this: 

When following the instructions in the [installation page](https://reasonml.github.io/reason-react/docs/en/installation.html), I get an error on the second step: 

```Error: theme react-hooks not found```

`bsb -version` shows `3.1.5`.

**Comment by anmonteiro** [comment]
I think the `react-hooks` theme has only been in BuckleScript from version 5.X. I would recommend to install 5.0.3.

**Comment by vgrafe** [comment]
Strange. I just followed the instructions... Also, I can't update bsb. Updating/reinstalling `bs-platform` does not fix the problem.

**Comment by phated** [comment]
@vgrafe something is probably messed up with your global install of bs-platform.  I'd recommend removing it completely and trying to install the latest from npm so you have 5.0.3 - you might also want to force remove your npm cache.

**Comment by vgrafe** [comment]
Sounds good - I'll try this evening.
