### ISSUE TITLE
PPX in playground doesn't support component naming

### ISSUE THREAD

**Issue by phated** [reasonml/reason-react#403]
I was trying to create a "Component Naming" sample in the playground but it doesn't seem to be supported.  No JS is generated with the following Reason code:

```reason
[@bs.config {jsx: 3}];

module Greeting = {
  [@react.component]
  let component = () => {
    <button> {React.string("Hello!")} </button>
  };
};

ReactDOMRe.renderToElementWithId(<Greeting.component />, "preview");
```

**Comment by ducaale** [comment]
this works for me

```Ocaml
module Greeting = {
  [@react.component]
  let make = () => {
    <button> {React.string("Hello!")} </button>
  };
};

ReactDOMRe.renderToElementWithId(<Greeting />, "preview");
```

**Comment by phated** [comment]
@ducaale `make` is the default name. This issue is specifically about naming components differently than `make`

**Comment by peterpme** [comment]
Hey folks,

For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Thank you and sorry about the delay. Please re-open if its still relevant!
