### ISSUE TITLE
What the different between ReasonReact.string and React.string 

### ISSUE THREAD

**Issue by fahmiirsyadk** [reasonml/reason-react#406]
im new in ReasonReact , when i try the code from intro example 

its using ReasonReact

```reason
[@react.component]
let make = (~name) =>
  <button> {ReasonReact.string("Hello " ++ name ++ "!")} </button>;
```

but when i lookup on the component page, its using React instead ReasonReact
```reason
[@react.component]
let make = (~name) => {
  let (count, setCount) = React.useState(() => 0);

  <div>
    <p> {React.string(name ++ " clicked " ++ string_of_int(count) ++ " times")} </p>
    <button onClick={_ => setCount(_ => count + 1)}>
      {React.string("Click me")}
    </button>
  </div>
};
```

i'm super exited to learn ReasonReact <3

**Comment by banacorn** [comment]
Here's what I found from the source:

https://github.com/reasonml/reason-react/blob/9df84d2b5b4ae88a30712be31036b0158342ef25/src/React.re#L5

https://github.com/reasonml/reason-react/blob/9df84d2b5b4ae88a30712be31036b0158342ef25/src/ReasonReact.re#L11

I'm also curious about the difference between `ReasonReact` and the new `React` module .

**Comment by fahmiirsyadk** [comment]
ohh its look like they wanna migrate to the new API

> The Record API is in feature-freeze. For the newest features and better support going forward, please consider migrating to the new function components.

**Comment by maxlibin** [comment]
https://reasonml.github.io/reason-react/blog/

```
This release also makes use of a new React namespace for APIs for all of the code related to this new way of writing components. Some functions have been copied over (like React.string, React.array) and many are new (like hooks)!
```

**Comment by phated** [comment]
There's no difference, it's just shorter and exists in the new namespace.  The old APIs are in feature freeze so you probably just want to use `React.string` instead.
