### ISSUE TITLE
How to use `React.useRef` to handle `ReactDOMRe.domRef` ?

### ISSUE THREAD

**Issue by banacorn** [reasonml/reason-react#407]
Here's how they handle refs with `useRef` in JS (from the [React Hooks doc](https://reactjs.org/docs/hooks-reference.html#useref))

```jsx
const inputEl = useRef(null);
return <input ref={inputEl} type="text" />
```

Since there are no documentation regarding `useRef` in Reason React, here's what I've come up with:

```reason
let inputEl = React.useRef(None);
<input ref=inputEl type="text" />
```

However , the types won't check:

```
Error: This expression has type React.Ref.t(option('a))
       but an expression was expected of type ReactDOMRe.domRef
```

It would be nice if the documentation can say something more about these built-in Hooks. Examples would also be helpful.

**Comment by banacorn** [comment]
Here are a few solutions:

```reason
let inputRef = React.createRef();
<input ref={ReactDOMRe.Ref.domRef(inputRef)} type="text" />
```

If `React.createRef` is not available in your current version, simply use:

```reason
let inputRef = React.useRef(Js.Nullable.null);
<input ref={ReactDOMRe.Ref.domRef(inputRef)} type="text" />
```

In case that you want to convert `Js.Nullable.t` to `option` beforehand:

```reason
let inputRef = React.useRef(None);
<input ref=ref={ReactDOMRe.Ref.callbackDomRef(elem =>
    React.Ref.setCurrent(inputRef, Js.Nullable.toOption(elem))
)} type="text" />
```

**Comment by pelamfi** [comment]
[Here is a StackOverflow question and answer adding React Hooks into the mix.](https://stackoverflow.com/a/58689472/1148030) (Linking it here, since this thread is a google hit when searching with appropriate keywords.)

Being a newcomer, I was able to put the solution together based on @banacorn s answer above. Thanks!
