### ISSUE TITLE
Is it okay to have side effects in useReducer?

### ISSUE THREAD

**Issue by banacorn** [reasonml/reason-react#408]
Before Hooks, we get to specify what we want to do in the reducer, by returning values of the type `ReactReason.update`.

However, with `useReducer`, it's not clear if it is okay to have side effects in the reducer
judging by the type `('state, 'action) => 'state`.

**Comment by baransu** [comment]
I would say it’s not ok. IMO reducers should be pure. If you want to have useReducer similiar to reducerComponent reducer there is gist by @bloodyowl https://gist.github.com/bloodyowl/64861aaf1f53cfe0eb340c3ea2250b47

It queues all sideeffects and runs them in useEffect.

**Comment by bloodyowl** [comment]
made a cleaner package that also adds the ability to cancel side-effects:
https://github.com/bloodyowl/reason-react-update

**Comment by baransu** [comment]
@bloodyowl Looks great!

**Comment by banacorn** [comment]
Thank you guys for making reducers great again!
