### ISSUE TITLE
Docs/Helper functions on common tasks like focusing a form field and getting an event value

### ISSUE THREAD

**Issue by justgage** [reasonml/reason-react#412]
The I wish there was some concept of "commonly used tasks" in the docs.

I can't for the life of me figure out how to focus a form field. While I'm ok asking in discord it seems that many of these tasks are very unitunitive to accomplish, many of which even require in depth knowledge of the bucklescript object syntax. Ideally there would be helper functions that would make these tasks easy, but barring that I would say that they should at least be documented.

For reference on how this affect beginners I know that things like getting a value out of an event of a form has been deemed ["a API designed by satan" by funfunfunction](https://www.youtube.com/watch?v=6MSksJhPcVA) which is one of the top videos when you search for ReasonML on Youtube.

**Comment by peterpme** [comment]
Hey @justgage 

Sorry about the delay! Please feel free to open a PR with some docs :smile: We'd love the help!

Closing this out for now
