### ISSUE TITLE
Add capture attribute for input element

### ISSUE THREAD

**Issue by pomali** [reasonml/reason-react#414]
```html
<input type_="file" accept="audio/*" id="capture" capture="microphone" />
<input type_="file" accept="audio/*" id="capture" capture=true />
```
Both statements throw type error like:
```
Error: The function applied to this argument has type ... 
...
=> ReactDOMRe.domProps
This argument cannot be applied with label ~capture
```
even though capture is valid html5 attribute.
https://www.w3.org/TR/html-media-capture/#the-capture-attribute

I could make PR but I'm not sure how to model `bool | string` property of this attribute. 

There was quite discussion in some React issues (https://github.com/facebook/react/issues/4784) because of this property.

**Comment by peterpme** [comment]
Hey @pomali 

For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Please feel free to open up a PR and we can go over functionality :smile:

Also please feel to join us on Discord https://discord.gg/reasonml

Thank you and sorry about the delay!
