### ISSUE TITLE
Tighter genType integration

### ISSUE THREAD

**Issue by phated** [reasonml/reason-react#415]
I talked a bit about this with @rickyvetter at ReasonConf and he thought we could make the integration better.  I wanted to open this as a point-of-reference (because I would totally forget).

**Comment by cristianoc** [comment]
@phated thanks for opening this.
The last couple of releases of genType, after ReasonConf, are about tighter integration (better naming for react dev tools, fix for importing components).
Would you take a look at those release notes and see if there are additional suggestions not currently covered.

**Comment by phated** [comment]
@cristianoc those release notes look great!  I'll have to give genType another try with the hooks API.

Something else @rickyvetter and I were discussing was removing the need to have a shim for this library.  I believe he said we could add `[@genType]` annotations to this codebase and then the things that usually would be shimmed would instead be generated.

**Comment by cristianoc** [comment]
Indeed, getting rid of any shims requirements would be good. Already considered that, just need to check the details and do it. One loses a bit of flexibility in customization, but hopefully things are stable enough that it does not matter in practice.

**Comment by peterpme** [comment]
Hey folks,

For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Thank you and sorry about the delay. Please re-open if its still relevant!
