### ISSUE TITLE
`useEffect3`–`useEffect7` bindings should use `[@bs.uncurry]`?

### ISSUE THREAD

**Issue by yawaramin** [reasonml/reason-react#425]
The bindings upto `useEffect2` take an auto-uncurried callback type as the first parameter, however the ones after that do not. Was this intentional, and if so why? If not, I suggest making them all uniformly auto-uncurry with `[@bs.uncurry]`. The function type itself can be elegantly lifted out because the annotation actually takes an integer payload indicating the function's arity, e.g.

```reason
// Types for descriptive purposes
type cancelEffect = unit => unit;
type effect = unit => option(cancelEffect);

[@bs.module "react"] external useEffect2: ([@bs.uncurry 1] effect, ('a, 'b)) => unit = "useEffect";
[@bs.module "react"] external useEffect3: ([@bs.uncurry 1] effect, ('a, 'b, 'c)) => unit = "useEffect";
// and so on
```

I'm not sure if this should be considered a breaking change or not, though.

**Comment by alexfedoseev** [comment]
It’s my fault, no idea how I missed that. I got food poisoned pretty hard, can’t submit fix right now, will do this evening or tomorrow.

**Comment by yawaramin** [comment]
No worries! I was also just thinking that this should not be a breaking change because no code change would be required at the callsite thanks to the way `[@bs.uncurry]` works.

**Comment by alexfedoseev** [comment]
I think it wasn’t released yet so all good.
