### ISSUE TITLE
Plans for desktop native like Revery?

### ISSUE THREAD

**Issue by satvikpendem** [reasonml/reason-react#428]
I was wondering about any plans to allow Reason React to compile down to a native desktop app like the [Revery](https://github.com/revery-ui/revery) project does. Is this something that's possible and might being pursued in the future?

**Comment by eldh** [comment]
Compiling react native apps for MacOS should be possible at some point after Catalina (+ Xcode 11) comes out.

**Comment by baransu** [comment]
Reason React is just binding to ReactJS as close to zero cost as possible. I think it's outside of scope of this project.

**Comment by satvikpendem** [comment]
Perhaps I am wondering about something like [Proton Native](https://proton-native.js.org), but in ReasonML rather than JS.

**Comment by jordwalke** [comment]
I think it's helpful to clarify what you mean by native. Using native platform widgets is one thing you might mean, and then compiling the code itself to native assembly is different, and probably out of scope for reason-react (though there's something we could do there in the long run).

**Comment by satvikpendem** [comment]
I mean write once, run everywhere such as on the web, as a mobile iOS/Android app, and on the desktop; basically, become a replacement for Electron. I originally meant native as in having a desktop app, but now that you mention it, native code compilation to each of those platforms is a plus, as Revery shows very fast performance if so, but it's not strictly necessary.

**Comment by peterpme** [comment]
Hey folks,

In an effort to clean up the repo (and given how old this issue is) I'm going to close this out for now. 

Sorry about the delay. Please re-open if its still relevant.

Thanks!
