### ISSUE TITLE
Labeled Parameter Error

### ISSUE THREAD

**Issue by nikgraf** [reasonml/reason-react#434]
This happened to me a handful of time, but also with beginners in workshops:

I wrote a component and forgot to make the prop `name` a labeled parameter:

Hello.re
```
[@react.component]
let make = name => <h1> {React.string("Hello " ++ name)} </h1>;
```

Index.re
```
ReactDOMRe.renderToElementWithId(<Hello name="Paris" />, "root");
```

The error message is quite confusing:

<img width="898" alt="Screenshot 2019-05-24 at 11 52 46" src="https://user-images.githubusercontent.com/223045/58319734-79400900-7e1a-11e9-9ed5-12036d769922.png">

Is there a way we can show an error if a function is decorated where one or multiple parameters aren't labeled parameters?

**Comment by peterpme** [comment]
Hey @nikgraf,

For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Thank you and sorry about the delay. Please re-open if its still relevant!
