### ISSUE TITLE
Provide example for migrating Jsx2 component to Jsx3

### ISSUE THREAD

**Issue by selenir** [reasonml/reason-react#436]
Currently there's a code sample which shows how you can create adapter module for Jsx3 components to use them with Jsx2 code via `wrapReactForReasonReact`. For other way around (wrapping Jsx2 components for Jsx3) there's only mentioned that you can use `wrapReasonReactForReact`, however there's no documentation on how one can use this function.

**Comment by jchavarri** [comment]
@selenir I added a PR with some documentation that explained this. Here's the link to the particular section, in case it helps: https://github.com/reasonml/reason-react/pull/424/files#diff-1eb83a7601b887a03489bb20d9f14643R101

**Comment by selenir** [comment]
@jchavarri Looks good, thanks!
