### ISSUE TITLE
Should warn if you don't provide labeled arguments for component

### ISSUE THREAD

**Issue by a7c** [reasonml/reason-react#439]
Suppose I write a component `TestComponent` and accidentally forget to use labeled arguments:
```
[@react.component]
let make = (text: string) => {
  <div> {ReasonReact.string(text)} </div>;
};
```
This compiles to
```
function TestComponent(_, text) {
  return React.createElement("div", undefined, text);
}
```
where the props (the first argument) are totally ignored. 

While the typechecker will complain that I need another argument if I try to use the component in Reason, the problem won't be caught until runtime if I use it in JS. Even then, the error is pretty far removed from the source of the  #problem.

Because omitting the tilde is a pretty easy mistake to make (especially for newbies), it would be nice if the ppx could emit a warning if it happens!

**Comment by peterpme** [comment]
Hey @a7c ,

For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Thank you and sorry about the delay. Please re-open if its still relevant!
