### ISSUE TITLE
<input /> min and max types are mismatched.

### ISSUE THREAD

**Issue by SebastianKurp** [reasonml/reason-react#441]
For the HTML tag `<input />`  with the type `number`, the min and max attribute types are mismatched.
For min, it requires the type of `int`, while for max it requires the type of `string`.

**Code to replicate the issue:**
```
[@react.component]
let make = (~value, ~min=0, ~max=10, ~step=1.) => {
  let (value, setValue) = React.useState(() => value);
  <input
    id="number"
    type_="number"
    placeholder="0"
    value
    min
    max
    step
    onChange={event => {
      let value = event->ReactEvent.Form.target##value;
      setValue(_value => value);
    }}
  />;
};
```

**The Error Message:**
![image](https://user-images.githubusercontent.com/16307737/59051839-66cec200-8853-11e9-8dac-aff20376c0fa.png)

Thanks in advance for fixing this ❤️

**Comment by sgny** [comment]
Despite the obvious bug, this is perhaps not trivial to fix as various types of input call for different types of `min`, `max`, `step` and `value`.

For example:
- for integers and floats, `min`, `max` and `step` should all be `int` or `float`
- for dates, `min` and `max` should be `Js.Date.t` whereas step should be `float` where `1.0` would be one day

There are other input types allowing various types for `min`, `max`, etc.

An easy way is to type all as `string`, but as that allow no type safety, a more useful approach might be to define multiple props, as below:
```
[@bs.optional] [@bs.as "min"]
min: string,
[@bs.optional] [@bs.as "min"]
minInt: int,
[@bs.optional] [@bs.as "min"]
minFloat: float,
[@bs.optional] [@bs.as "min"]
minDate: Js.Date.t,
```

I have created a PR with this approach, see #442.

**Comment by peterpme** [comment]
This will be released soon. Closing this issue for now. Thanks @SebastianKurp !!
