### ISSUE TITLE
Minor documentation update

### ISSUE THREAD

**Issue by jdeisenberg** [reasonml/reason-react#445]
At https://reasonml.github.io/reason-react/docs/en/installation (file `docs/installation.md`), change:

> The `react` theme offers a lightweight solution optimized for low learning overhead and ease of integration into an existing project.

to:

> The `react-hooks` theme offers a lightweight solution...

**Comment by peterpme** [comment]
Hey @jdeisenberg 

Thank you for this! Feel free to open up a PR :smile:
