### ISSUE TITLE
ReasonReact dependencies use a different version of react

### ISSUE THREAD

**Issue by tmattio** [reasonml/reason-react#447]
Hi!

When using a local dependency with reason-react, it seems that the dependency and the project will use different versions of react. This causes the app to crash whenever we use a library component that uses hooks. 

![image](https://user-images.githubusercontent.com/6162008/59511570-a06f8080-8e84-11e9-965c-47e1b6fbdbb5.png)

There is a dependency warning on the compiler output as well:

![image](https://user-images.githubusercontent.com/6162008/59511618-c39a3000-8e84-11e9-899f-3b2e7c34f955.png)

I created a repo to reproduce the bug easily:
https://github.com/tmattio/multiple-reason-react-bug

It is a contained bug that only happens if using a local version of the dependency that installed the node modules. But it is a blocker to develop the package and the library at the same time, where you would likely create a `npm link` to the library.

I also tried playing with the configuration of the library (moving react, reason-react, etc. to peerDependencies), but it does not seem to have an effect.

**Comment by tizoc** [comment]
@tmattio where you able to find a workaround for this? I'm experiencing the same problem now.

**Comment by tizoc** [comment]
Just switched this project to use Yarn as suggested [here](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react), that fixed the issue for me.

**Comment by tmattio** [comment]
@tizoc No, I didn't find any workaround. I just delete `node_modules` in the dependency and re-install the packages.

Did you use yarn resolutions? Because I'm using yarn and I am still hitting this issue.

**Comment by tizoc** [comment]
@tmattio I didn't have to use resolutions. Deleting `package-lock.json`, running `yarn install` and then rebuilding the project was enough. It also fixed the issues I was having with `moduleserve`.

**Comment by tizoc** [comment]
Btw, what is the output of `npm ls react` ? I used to have two copies before switching to yarn, now I have:

```
├── react@16.13.1 
└─┬ reason-react@0.7.0
  └── react@16.13.1  deduped
```

**Comment by peterpme** [comment]
Closing this out for now. If this is still an issue, please re-open. Thanks!
