### ISSUE TITLE
[@react.component] loses information about optional params option('a) type

### ISSUE THREAD

**Issue by fakenickels** [reasonml/reason-react#451]
The current ppx lets you compile this code without requiring you to deal with the option type `id`

```reason
[@react.component]
let make = (~id: string=?) => <div id />;
```

Where this, what is supposed to be the correct version, doesn't
```reason
[@react.component]
let make = (~id: string=?) => <div ?id />;
```

**Comment by rickyvetter** [comment]
Looking into this. FWIW the correct version is:

```reason
[@react.component]
let make = (~id: option(string)=?) => <div ?id />;
```

**Comment by rickyvetter** [comment]
The fix for this is kinda disappointing and might break in some cases. I'm testing it on our WWW codebase. Will hopefully have a PR for public testing once I've ironed the edge cases out.

**Comment by gaku-sei** [comment]
I second this, it can be very confusing especially when mixing components defined in Reason, and other bound using `external` where `~xxx: string=?` is valid.

A non breaking warning could help a lot. Any update @rickyvetter ?

**Comment by peterpme** [comment]
Hey folks,

In an effort to clean up the repo (and given how old this issue is) I'm going to close this out for now. 

Sorry about the delay. Please re-open if its still relevant.

Thanks!
