### ISSUE TITLE
wrapReasonReactForReact doesn't work on components with open parameters

### ISSUE THREAD

**Issue by zbaylin** [reasonml/reason-react#453]
I was trying to create temporary JSX v3 bindings for https://github.com/ahrefs/bs-recharts, and ran across an issue.

Any time a component parameter has an open type (namely `Js.t({..})`) the compiler throws the following error:

`This expression's type contains type variables that can't be generalized:`

Is there any way of getting around this, or do I have to rewrite each component individually?

**Comment by peterpme** [comment]
Hey @zbaylin 

For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Thank you and sorry about the delay. Please re-open if its still relevant!
