### ISSUE TITLE
router fails on trailing /

### ISSUE THREAD

**Issue by webmstk** [reasonml/reason-react#458]
Steps to reproduce:
```
bsb -init router_app -theme react-hooks
```
index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>ReasonReact Examples</title>
</head>
<body>
  <div id="app"></div>

  <script src="Index.js"></script>
</body>
</html>
```

Index.re
```
ReactDOMRe.renderToElementWithId(<App />, "app");
```

App.re
```
[@react.component]
let make = () => {
  let url = ReasonReactRouter.useUrl();
  switch (url.path) {
  | ["page1"] => <div> {ReasonReact.string("page1")} </div>
  | [] => <div> {ReasonReact.string("root")} </div>
  | _ => <div> {ReasonReact.string("Page Not Found.")} </div>
  };
};
```

http://localhost:8000/page1 shows "page1"
http://localhost:8000/page1/ fails with `GET http://localhost:8000/page1/Index.js 404 (Not Found)`

**Comment by peterpme** [comment]
Hey @webmstk,

For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Thank you and sorry about the delay. Please re-open if its still relevant!

**Comment by tony-go** [comment]
Hi Folks 👋 

I get a similar issue:

```ml
[@react.component]
let make = () => {
  let url = ReasonReactRouter.useUrl();

  switch (url.path) {
  | ["page"] => <div> {ReasonReact.string("page1")} </div>
  | [] => <div> {ReasonReact.string("root")} </div>
  | _ => <div> {ReasonReact.string("Page Not Found.")} </div>
  };
};
```

When I go to `/page` -> File not found. :(

My deps: 

```json
  "dependencies": {
    "react": "^16.8.1",
    "react-dom": "^16.8.1",
    "reason-react": "0.9.1"
  },
  "devDependencies": {
    "bs-platform": "7.1.1",
    "moduleserve": "^0.8.4"
  }
```

Let me know If I could help ^^

**Comment by yawaramin** [comment]
@tony-go you mean when you go to `/page/` (with a trailing slash), you get 'Page Not Found' rendered on the page?

**Comment by tony-go** [comment]
Nope. I mean I have a white page with " File not found. :("

I try with another repo and it seems to work. I have not the version of the packages here. I'll post it here later.
