### ISSUE TITLE
[@react.component] loses location for warnings

### ISSUE THREAD

**Issue by Coobaha** [reasonml/reason-react#459]
Hi @rickyvetter 

```
module Broken = {
  [@react.component]
  let make = (~value) =>
    switch (value) {
    | Some("") => React.null
    };
};
module Correct = {
  [@react.component]
  let make = (~value) => {
    let _fixesWarning = ();
    switch (value) {
    | Some("") => React.null
    };
  };
};

```

```

Warning number 8
OCaml preview

You forgot to handle a possible case here, for example: 
None


Warning number 8
OCaml preview 11:7-70

You forgot to handle a possible case here, for example: 
None
```
https://reasonml.github.io/en/try?rrjsx=true&ocaml=LYewJgrgNgpgBAIQE4gNYwHZwLwCg5wDOALkhAMbH4FyzFzACG6cAfgG6NQTw7U0NGxcgAs4nbvADuAS2JiAPnAAUygMohg8ZQCIdASn0BtAAIwAHgAcoM8nID6jJHICecALr64AWgB8cACUYRkoAOgxoKH4aUxMkYLDyTUsQDEx6dzhqTDBcUEhYOABhECR4yj4CEjJKaLpBFg4uHgI8AQJ6+wAzGXMYQgB1JwwZDABzHBUvUeiCJmExCRbZeTglVQ0tFT1DUwtrWwcnVw8vP0CE4nDI2bhY+JCrpOAUtIwM7IwwIA

**Comment by peterpme** [comment]
Hey @Coobaha,

For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Thank you and sorry about the delay. Please re-open if its still relevant!
