### ISSUE TITLE
Making "props" property for JS interop optional

### ISSUE THREAD

**Issue by SllyQ** [reasonml/reason-react#46]
When you do [interop with JS](https://reasonml.github.io/reason-react/#reason-react-interop-with-existing-javascript-components) (also applies to [working with children](https://reasonml.github.io/reason-react/#reason-react-working-with-children)) you are forced to always pass props to a component, however some components are designed not to take any props and then you are forced to pass empty object. This is both inconvenient and seems like a source of problems for beginners, so I think the argument should be made optional.

**Comment by cristianoc** [comment]
Making the argument optional has the disadvantage that if you forget to pass props, you won't get a warning.
We could perhaps make a constant emptyProps available, or something.

**Comment by cristianoc** [comment]
Or wrapJsForReasonNoProps.

**Comment by phated** [comment]
This should be solved by the 0.7.0 zero-cost bindings (if you don't have any named params, no props will be passed).  See https://reasonml.github.io/reason-react/docs/en/components#interop for more interop details.
