### ISSUE TITLE
Add event capturing support

### ISSUE THREAD

**Issue by aw-yt** [reasonml/reason-react#462]
I tried the React's way of event capturing for instacne by using `onClickCapture` but it doesn't work. I also tried searching through Reason React code base but couldn't find any reference to event capturing seems like it's missing the binding.

**Comment by peterpme** [comment]
Hey @aw-yt 

In an effort to clean up the repo (and given how old this issue is) I'm going to close this out for now. 

Sorry about the delay. Please re-open if its still relevant.

Thanks!
