### ISSUE TITLE
Documentation: add info about using `useState` with `ReactEvent` target values

### ISSUE THREAD

**Issue by johnridesabike** [reasonml/reason-react#476]
This seems to be a common pitfall among developers converting from ReactJS. In JavaScript, you can do the following:
```js
const [count, setCount] = useState(0);
// later in the component:
setCount(event.target.value);
```

When writing the same component in Reason, developers tend to incorrectly write it like this:
```re
let (count, setCount) = React.useState(_ => 0);
// later in the component:
setCount(_ => ReactEvent.Form.target(event)##value);
```

This raises an error from React, and the state will fail to update correctly. The issue is that `setState` dispatches are executed after React has cleaned up the synthetic event. Because the event target's value is accessed within a function, the event doesn't exist anymore by the time the function executes.

Correct code:
```re
let (count, setCount) = React.useState(_ => 0);
// later in the component:
let newCount = ReactEvent.Form.target(event)##value;
setCount(_ => newCount);
```

I'm happy to submit a PR with clarifying information. Is there a preference on which part of the docs it should go in? E.g.: in the Components page, on a page under ReactJS Idioms Equivalents, or somewhere else?

**Comment by peterpme** [comment]
Hey @johnridesabike,

This is awesome! Would love your help on this. I think a page "ReactJS Idioms Equivalents" would be awesome!

Thank you!
