### ISSUE TITLE
Typing children recursively

### ISSUE THREAD

**Issue by rtsao** [reasonml/reason-react#478]
I was wondering if something similar to https://github.com/facebook/flow/issues/6611 would be possible with ReasonReact.

In short, would it be possible to type component that accepts only children of a specific type, fragments containing only that specific type, or components that return the same specific type?

For example, a `List` component that should only render `Item` components:

```
<List>
  <Item />
  <ComponentThatRendersASingleItem />
  <>
    <Item />
    <Item />
  <>
  <ComponentThatRendersSeveralItemsInAFragment />
<List>
```

**Comment by TomiS** [comment]
I also express interest in something like this. Being able to type exactly what kinds of children are allowed enables at least a few of use cases:
1) Design systems: Enforce on type level how developers are allowed to nest components (Item in List, Header in Card, etc)
2) Some edge cases where parent component needs to control the styles of the child, and it needs to be able to trust that the child is of certain specific type.
3) Parent overloading props of a child (again, not very common but sometimes needed and very unsafe if parent cannot trust children are not of certain type)

**Comment by peterpme** [comment]
Hey folks, 

Do you mind moving this convo to ReasonML Forums located here: https://reasonml.chat/

Thanks!

**Comment by hoichi** [comment]
For the record, it _has_ been moved to https://reasonml.chat/t/typing-children-recursively/2345
