### ISSUE TITLE
error when file of record module is moved to another folder but resolve after reloading editor

### ISSUE THREAD

**Issue by putrasurya** [reasonml/reason-react#482]
i'm using WSL

bs-platform: 5.0.6
text-editor: vscode
extension: reason-vscode

steps to reproduce:

1. create react reason app 
bsb -init my-react-app -theme react-hooks

2. run the app
yarn start or npm run start

3. create new file for /src/School.re and fill with this
`type person = {
  age: int,
  name: string
}`

4 insert new code into /src/Demo.re
`let me: School.person = {
  name: "my name",
  age: 25
}`

5. create new folder for /src/folder

6. move School.re to /src/folder

7. now you will get an error from terminal like this one
![image](https://user-images.githubusercontent.com/3635850/66843670-4ea44780-ef97-11e9-8d23-de0a2b50d654.png)

8. make an some edit to /src/Demo.re file and saved 
just insert some whitespace

9. then you will get an error 
![image](https://user-images.githubusercontent.com/3635850/66843812-7d222280-ef97-11e9-9fdf-8d1cb8bb77f2.png)

alternative solution is to "Reload the VSCode"
![image](https://user-images.githubusercontent.com/3635850/66843878-91feb600-ef97-11e9-8121-8f5c686d3dee.png)

and re-start the app, and error will gone

**Comment by rickyvetter** [comment]
Hey @putrasurya this is an issue with the VSCode extension. I'd recommend making an issue on https://github.com/reasonml-editor/vscode-reasonml with your repro steps. Sorry this isn't working for you!
