### ISSUE TITLE
FAQ section needs page about Redux/global state

### ISSUE THREAD

**Issue by yawaramin** [reasonml/reason-react#486]
One of the most frequent questions people have when evaluating ReasonReact, especially migrating an existing codebase from ReactJS, is how to handle global state/whether there are Redux bindings/whether there is a Redux equivalent (I consider these to fall under the same general question).

We need an FAQ page that answers these questions.

**Comment by peterpme** [comment]
Hey @yawaramin 

In an effort to clean up the repo (and given how old this issue is) I'm going to close this out for now. Feel free to re-open.

Also if you'd like to open a PR up and write the FAQ, I can help you get it merged in. Thanks!!
