### ISSUE TITLE
Bump React.js version

### ISSUE THREAD

**Issue by RomanGalochkin** [reasonml/reason-react#492]
Please, bump the version of React JS to 16.11.0.

**Comment by flash-gordon** [comment]
Current dependencies are not in conflict with 16.11: https://github.com/reasonml/reason-react/blob/9effd79bcf8cd317e030fbd5341a3f5456573405/package.json#L27-L30

**Comment by RomanGalochkin** [comment]
You are right. But this should be included into "peerDependencies". http://npm.github.io/using-pkgs-docs/package-json/types/peerdependencies.html

**Comment by RomanGalochkin** [comment]
I have modified this package and changed "package.json" on "peerDependencies" what is working perfect.

**Comment by RomanGalochkin** [comment]
Please, consider this PR too:
https://github.com/reasonml/reason-react/pull/361

**Comment by peterpme** [comment]
Hey @RomanGalochkin 

We're working on merging this PR in so I'm going to close this out. Thanks!
