### ISSUE TITLE
Add bindings for React.Children

### ISSUE THREAD

**Issue by selenir** [reasonml/reason-react#494]
I think bindings for React.Children may be useful for many folks.
I run onto a problem while trying to map over component's children. I had to use Array.map, but it forces the children type to be `array(React.element)` instead of `React.element` which forced me to pass the children as an array and that looks awkward:
```
<Component>
  [|
    <Child />
    <Child />
  |]
</Component>
```

If we had bindings for `React.Children.map` with type `React.element => React.element` it would solve this problem.

**Comment by selenir** [comment]
It looks like bindings were already added in 4ea098b but are not released on npm yet. When can we hope for them to be released?

**Comment by peterpme** [comment]
Hey @selenir,

we're working on a new release. Closing this out for now. 

Thanks!
