### ISSUE TITLE
Pass 1 or many children to component that uses ReactDOMRe.createElement

### ISSUE THREAD

**Issue by jchavarri** [reasonml/reason-react#496]
Kind of related to https://github.com/reasonml/reason-react/issues/410.

Maybe this is not an actual issue, but a chance to improve documentation.

If one tries to create a component `T` that:
- uses `ReactDOMRe.createElement` 
- just passes `children` through blindly

Something like this:

```reason
module T = {
  [@react.component]
  let make = (~children) =>
    ReactDOMRe.createElement(
      "div",
      ~props=ReactDOMRe.objToDOMProps({"data-tooltip-id": "foo"}),
      children->unsafeToArrayEl,
    );
};
```

Right now, `ReactDOMRe.createElement` binding type forces every consumer to pass explictely an `array(React.element`) as `children`

https://github.com/reasonml/reason-react/blob/19fec02c8c432a4cb15839381131405991d7bbac/src/ReactDOMRe.re#L2105-L2109

This is quite annoying, as it breaks the whole purpose of the ppx, which allows to pass 1 or many children seamlessly without issues, which is awesome.

If one unsafely converts children from `React.element` to `array(React.element)` [it works](https://nit.sketch.sh/?code=NoAQRgzgdAxg9gOwGYEsDmACA3gKwgDwC4MBmAXwF0BuAKBoHoAqDAJQFMBDCRdjmAFwxgUCACYi0EDPzitOAgCIB5ALIYkAVwQCUiKW3wAHNgIwADDgCdLHAJ4AKXgKhsANmwC2bBPwCUZoQ1+GjYANzZLWwB3AAsItgw3CATHeUEPOFENdwAaDAApAGUADQxDQ3xE-hhfDERXW3Mnfhd3Lx8AlCkNZNEMRnoQ-H4IhA5XDC0IDiQ2ABU4AEFrOwBRV2Jm1s9vQQBeAD4MKxsHLbcdn1q9jAAiAFIUUV2Ufltb2hoMrPcMOYwblgaBgMKBLGlYHAPIZELsKMCMO50hwANYJG72AB+MBiKFconBCGuBwRIOayhU7Fg4I4I3Wl349lJILu4lCtxyzJBmMMljghgge3JqipcDAOAWFIACnyBfYsLdRLSOABaGRwVz8FCGFVPW7EW5IOBwW5kXyclksnF4gneFUHKYzeZLFa2dYWlm+WhkT7CylsKCE56WBb09r8ADqrxiAElREyQQAeNkky2JuZHW6w634272rYQfiWCQYRP0DPM9OZ-hRE35iGF4sITC3DA520IPMHAtFktlitJ+gpj23Plwfi3GheoA). But I'm not sure if this is ok.

I understand the `array(element)` constraint comes from BuckleScript `[@bs.splice]` requirement. But if one passes some parameter as the array, the compiler is not able to inline the application and still calls `apply` ([example](https://reasonml.github.io/en/try?rrjsx=true&reason=NoAQRgzgdAtg9gEwK4BsCmACARAJzQQwGMAXLAXQ1EigDd8cBLfBBwsgKDQA9i0cA7fCgyE8+XgFF0MNP2IAuDAAoIxRvwDmAGgwA-AA444+iIoZyAvAH4d9HPgCeKteY0BKNxgsA+DKvUaXuwY2KIEktKypADc7OzoxBiJFsqEABYMKAh4-J4+GOxh4mhSaDJySlgsNFg6BkYmFgBMOumZ2bJusUA)).

Shouldn't there be a binding that allows to:
- create host DOM elements
- with custom properties
- and typing `children` just as `React.element`?

cc @rickyvetter

**Comment by rickyvetter** [comment]
> But I'm not sure if this is ok

It is not safe, no.

I think it's a good idea to deprecate all of these APIs in favor of `React.jsx` - https://github.com/reasonml/reason-react/pull/566. We will leave one version of createElement and which does not allow child passing. You can use it by adding `children` to props object directly.

**Comment by jchavarri** [comment]
Thanks for clarifying :) I will check the new `React.jsx` work 👍
