### ISSUE TITLE
Cannot forward ref to components

### ISSUE THREAD

**Issue by EliaECoyote** [reasonml/reason-react#497]
I'm experiencing an issue where forwarding a ref from a component to another generates this error:
``` 
Error: The function applied to this argument has type
         (~key: string=?) => {. }
This argument cannot be applied with label ~ref
```
as if the component is not expecting a ref by default.

The issue can be reproduced with the following snippet:
```reason
module Child = {
  [@react.component]
  let make =
    React.forwardRef((_, someRef) =>
      <div
        ref=?{
          someRef
          ->Js.Nullable.toOption
          ->Belt.Option.map(ReactDOMRe.Ref.domRef)
        }
      />
    );
};

type element = React.Ref.t(Js.Nullable.t(Dom.element));

module Parent = {
  [@react.component]
  let make = () => {
    let elementRef: element = React.useRef(Js.Nullable.null);
    <Child ref={elementRef->ReactDOMRe.Ref.domRef} />;
    /*
       **************************************************************************
       ** The *ref={elementRef->ReactDOMRe.Ref.domRef}* statement produces the **
       ** following error:                                                     **
       **************************************************************************
       Error: The function applied to this argument has type
         (~key: string=?) => {. }
       This argument cannot be applied with label ~ref
     */
  };
};
```

I don't understand if it's possible to specify that the component expects a ref. 
I mean, I expect that `React.forwardRef` or `[@react.component]` automatically takes care of that on the receiver component.

---

Here's a [nit.sketch.sh link](https://nit.sketch.sh/?code=LYewJgrgNgpgBAYQBYEspjgXjgbwFBxwDaAAgE4wCGAxgC4B01IwADiAHYzu0C6BcsWnGCUA1vEz9CAJSp16AMxBkA7pTJhZCgBTaA+gBo4AZ2YwtASiwA+KYTgAeMCgBud+3AoLMAfnweAkzMtdwCAWmsAKWN6ADloKEoAI1h6WhAAeRZaFA5QjwiAIRgoBiycjnoRFm1ZGloAEQyAWVl6LXowZkt8uABfUIB6Ww8LAG48Pom8WgBPFngSmGAuIWw6+Q7abWi4hOTU7YbmeiWV7gtxvDxQSFg4AAV1VaxcflIKesZmNk5uPkIgmEYgkcG0Vkw1jeHiBZ1WWgAXHA4dxXhsGBBjOYYDpdvEoIkUjB6OwElcPA5kGgMF5MDh0U1WsSOl1gFptCjaJY+nBhhMPIMAFT5QWisXiiWSqXSmWyuXSkWCuAAFSQ8EFtJwnK0EQZLTaLO6OL6SuMtEotGWLxYZHAEGoMGMcFoargosVcCUBJAKhQ7AA5siyLayEjAuGI5Go9G3cLw-KE4mk8nxfkAKLB5RI1XwBQQdh0XLsOCUFgsKAoGAYdLO1BO9T+iDnIRIShOuYLXpggB+4lmSLNZD9-t8EKhOHo-XyqpQ9bIjebcGolHY7BAQiS8FL5crGF9LoEyRKcG7XncgsG-CmkzGQA) where you can actually see the error:

Notice that by avoiding the usage of `[@react.component]` on the receiver component, the issue is no longer there.
Here's another [nit.sketch.sh link](https://nit.sketch.sh/?code=LYewJgrgNgpgBAYQBYEspjgXjgbwFBxwDaAAgEYDOAdCGQFYC6cMAHgC4wBOAdgIZRxgvANYwACpxAAHCgC44ACgKE4AP04wAZvIBKMXgGM2AEQDyAWT1U9mqm0wB+ADTLCEbijYvCASiwA+OAB9LDgAIjCAbjxlWDZBEXhsPUM2Kk0QTgB3Xk4wGwUFIKc4ChBgGBs-TH9XOAAeMBQANzgNTUd8FRUyips6wgBafwApagA5aCheMlg7EFMpNhQQbgG4YYAhGCg0xeXVqiEpBRSjM0sYay0qMHKquoBfOAB6f284H2jH6LxQSFgcDEuRg3Hi2C6xBIGlSVAM5Skq1BbAYsRg8SEolCCmqgUhhDizFgFTBNlCZzSEAolS0CjGVEmUGmsyu3CmXzq9WQaAw7UwOApFysNlu91pOxgJLYVWeb2ihB+eEVQA) without `[@react.component]`

**Comment by osener** [comment]
Try changing `    React.forwardRef((_, someRef) => ... )` to `    React.forwardRef((someRef) => ... )`.

When you're expecting props it would be something like 
```reason
[@react.component]
let make =
  React.forwardRef((~className=?, ~children, ref_) =>
    <div
      ?className
      ref=?{
        Js.Nullable.toOption(ref_)->Belt.Option.map(ReactDOMRe.Ref.domRef)
      }>
      children
    </div>
  );
```

**Comment by EliaECoyote** [comment]
Thanks @osener, that was it!
The fact that I wasn't able to find an example for `forwardRef` usage on ReasonReact docs and the fact that the js syntax is `React.forwardRef((props, ref) => (...))` confused me

**Comment by yawaramin** [comment]
@EliaECoyote that's a good point. I think a PR with an example would be appreciated :-)

**Comment by osener** [comment]
@EliaECoyote technically it's still the same, it's just that `[@react.component]` does that for you. 

See the documentation about the PPX transformation here: https://reasonml.github.io/reason-react/docs/en/components

In the end you end up with two functions, `make` which takes the props and renders the component, and `makeProps` which constructs the props object.

You can see the JS output here: https://reasonml.github.io/en/try.html?rrjsx=true&reason=NoAQRgzgdAxg9gOwGYEsDmACA3gKwgDwC4MBmAXwF0BuAKBtACcBTAQxgBdY4BbAB0SYJ2FGgBsm7DNxYBrJhgC8NDBgBKrDlCRwGAdxYMAJuqQAKUwD8YolhAgA5FtyYKA-ABoMVgBYpRh5gRPZiQAfQBKRQA+ZRUMAB5DFAA3WLiMV2tbBycmNLiQtyx89IApaHsAV1EbMHEodjgAeV52FERTEIiAWiiAISZRTha2xChpXlN1NnYAESaAWXUoEyhDHhNwkowyGPSVGF9-QPz4gHok5L2McKogA
