### ISSUE TITLE
Reason React npm run serve not working.

### ISSUE THREAD

**Issue by yaldram** [reasonml/reason-react#504]
Hello ReasonReact Team/Community,
I have completed learning ReasonML, I fell in love with the things it brings to the table. I just wanted to try out ReasonReact and see how it compares to my current stack of React with TypeScript.

I ran the following commands as the Docs suggest : -
`
npm install -g bs-platform@6.2.1
`
`
bsb -init my-react-app -theme react-hooks
`
`
cd my-react-app
`
`
npm install && npm start
` 

But when I run `npm run server`  and navigate to localhost:8000 I get an error `localhost sent an invalid response.`

I opened package.json and saw that we are using `moduleserve` I checked their README but could not get this working.

When I ran index.html I got file not found moduleserve/load.js, meaning moduleserve is not generating a directory with load.js file.

Please help, I really want to try out ReasonReact thank you.

**Comment by devSeb** [comment]
In the first time , i follow the Installation of the website and it doesn't work.

If you follow the documentation 'installation' of the readme it's work 
* Not install bs-platform@6.2.1 


npm install --global bs-platform
bsb -init my-react-app -theme react-hooks
cd my-react-app && npm install && npm start
# in another tab
npm run server

**Comment by peterpme** [comment]
Hey, closing this out for now in an effort to clean up issues. If this is still an issue, please re-open! Thanks!
