### ISSUE TITLE
bs-platform 6 in installation page

### ISSUE THREAD

**Issue by kamilkuz** [reasonml/reason-react#508]
In documentation, in installation page: https://reasonml.github.io/reason-react/docs/en/installation
there is instruction to install bs-platform 6.2.1, but the newest is 7.0.1. In my opinion it always should be without version to always get newsest (like in readme).

**Comment by FranklinChen** [comment]
It seems things don't build yet with version 7.

**Comment by kamilkuz** [comment]
I'm using it with bs-platform 7 and everything is working

**Comment by Coobaha** [comment]
I can confirm that there are issues with bs-platform 7.3.1 
```
 FAILED: src/React.cmj src/React.cmi ~/Project/node_modules/reason-react/src/React.js
 ~/Project/node_modules/bs-platform/darwin/bsc.exe -bs-package-name reason-react  -bs-package-output es6:src -color always -I src -w a -bs-no-version-header -o src/React.cmj src/React.reast
   We've found a bug for you!
   ~/Project/node_modules/reason-react/src/React.re

   src/React.cmi
 is not a compiled interface for this version of OCaml.
 It seems to be for an older version of OCaml.

 [24/37] Building src/ReactDOMRe.reast
 [25/37] Building src/ReasonReactOptimizedCreateClass.cmj
 FAILED: src/ReasonReactOptimizedCreateClass.cmj src/ReasonReactOptimizedCreateClass.cmi ~/Project/node_modules/reason-react/src/ReasonReactOptimizedCreateClass.js
 ~/Project/node_modules/bs-platform/darwin/bsc.exe -bs-package-name reason-react  -bs-package-output es6:src -color always -I src -w a -bs-no-version-header -o src/ReasonReactOptimizedCreateClass.cmj src/ReasonReactOptimizedCreateClass.reast
   We've found a bug for you!
   ~/Project/node_modules/reason-react/src/ReasonReactOptimizedCreateClass.re

   src/ReasonReactOptimizedCreateClass.cmi
 is not a compiled interface for this version of OCaml.
 It seems to be for an older version of OCaml.

 [26/37] Building src/ReactEvent.cmi
```

This happens with fresh `node_modules`, running clean before build helps.

**Comment by FranklinChen** [comment]
I was partially wrong: the problem I encountered after `bsb -init my-react-app -theme react-hooks` and `npm install` and `npm start` had to do with a mismatch of OCaml versions for `.cmi` files so when I deleted all the `.cmi` files with `find . -name '*.cmi' | xargs rm` everything worked.

**Comment by kamilkuz** [comment]
> It seems things don't build yet with version 7.

@FranklinChen Okey i only tested it on bs-platform 7.0.1 and it was working. I didn't check for newer.

**Comment by yawaramin** [comment]
@Coobaha it should build correctly if you do `bsb -clean-world` then `bsb -make-world`. The `reason-react` npm package was mistakenly shipping with compiled intermediate files, but these have been removed in #518 and the next published version should leave them out.

**Comment by Coobaha** [comment]
> @Coobaha it should build correctly if you do `bsb -clean-world` then `bsb -make-world`. The `reason-react` npm package was mistakenly shipping with compiled intermediate files, but these have been removed in #518 and the next published version should leave them out.

Yeap that’s what I wrote :) you can also just call `bsb -clean-world -make-world` but we have a lot of people working with the code case where reason packages are used, and clean build ads some time. So we are just staying on 7.2.2 😄

**Comment by peterpme** [comment]
Hey everyone,

Everything should be working with latest version of bs-platform. We also have a new release that will upgrade bs-platform, etc. 

If you still have issues, please re-open. Thanks!
