### ISSUE TITLE
`to` attribute still needs prepending instead of accepting a trailing `_`

### ISSUE THREAD

**Issue by jfrolich** [reasonml/reason-react#509]
This is a bug, because a trailing `_` should be the recommended way and prepended deprecated.

This is on Bucklescript 7.1.0

Related: 
- https://github.com/reasonml/reason-react/issues/204
- https://github.com/reasonml/reason-react/issues/204

**Comment by jfrolich** [comment]
Not sure if this might be a bucklescript bug

**Comment by peterpme** [comment]
Hey @jfrolich 

In an effort to clean up the repo, I'm going to close this out. Please re-open if this is still an issue!

**Comment by jfrolich** [comment]
Great effort to clean the repo, but I think this still should be resolved, as it's inconsistent. I can not reopen this by myself.

**Comment by peterpme** [comment]
Hey @jfrolich, thanks for reaching out! I think it is a bucklescript bug. Do you mind creating an issue here? https://github.com/BuckleScript/bucklescript/issues

Thank you!!!

**Comment by jfrolich** [comment]
Ah the ppx is part of the Bucklescript Repo, I see. ✅ Thanks!
