### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by gaku-sei** [reasonml/reason-react#513]
It's been a while since the last release, and 110 commits have been pushed since that day, any plan to release a new version soon?

**Comment by sorenhoyer** [comment]
Was pretty excited to learn reasonml, so a bit disappointing to see how this library is on life support. :-/

**Comment by cristianoc** [comment]
@sorenhoyer exactly what missing featrure is blocking you from doing your work?

**Comment by cem2ran** [comment]
@cristianoc I personally need the Children api. I can get around the fact that this including later commits have not been published by consuming from master, but they really should have been published? Not sure if there are any blockers? @rickyvetter 

It does reflect a bit poorly on the status of the Reason React repo as expressed in this issue.

**Comment by cristianoc** [comment]
@cem2ran thanks, that's indeed a good feature.
I think there's a new release planned.

**Comment by rickyvetter** [comment]
Hey folks. Sorry about the really slow movement here and thanks for bringing it up. Working on a release and reviewing issues/PRs now. Hope to get a release this week.

**Comment by rickyvetter** [comment]
Just released a patch version 0.7.1. Please take a look. Batching together some potential breaking changes for an 0.8.0 release for later this week. I'll leave this issue open as a tracker until then and then close.

If you all have any issues with 0.7.1 or recommendations for 0.8, please let me know!

**Comment by gaku-sei** [comment]
That's really great! Thank you @rickyvetter. Updating now 😄

**Comment by TomiS** [comment]
@cem2ran By any chance, is this "Children api" the same thing that relates to controlling which children are allowed on type level? Because that'd be sweet.

Ps. While technically irrelevant, the release frequency of this repo should probably be considered as a communication/marketing channel even if it was probably not intended as one. People do come here and check when was the last release and make assumptions based on that. My colleague actually asked about this very thing a few months ago.

**Comment by cem2ran** [comment]
@TomiS unrelated. It was about having this released: https://github.com/reasonml/reason-react/pull/393

Feel free to open a new issue regarding the above if it doesn't exist yet. 
Otherwise I think this issue can be closed @rickyvetter @cristianoc

**Comment by TomiS** [comment]
@cem2ran Ah, I see. I was just referring to the future improvement/possibility Ricky mentioned in his talk a little while ago.

**Comment by peterpme** [comment]
Hey everyone,

I'm closing this issue out because we'll have some new releases soon :smile:

**Comment by rickyvetter** [comment]
0.8.0 is out right now. Please open new issues if you run into any issues or you'd like to request features/changes. Thanks all! Enjoy.
