### ISSUE TITLE
ReasonReactRouter.useUrl() path is undefined.

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [reasonml/reason-react#517]
With url `http://localhost:3000/`.
```
  let url = ReasonReactRouter.useUrl(); //http://localhost:3000/fields
  Js.log(url); // [["fields", 0], "", ""]
  Js.log(url.path); // undefined
```

**Comment by yawaramin** [comment]
The first log output makes sense based on the documentation: https://reasonml.github.io/reason-react/docs/en/router#match-a-route

The second log output does not make sense. The `url` was just logged and it clearly includes a defined `path`. So `url.path` should definitely not be `undefined`. If you could upload a small repro project that shows this issue, that would be very helpful.

**Comment by a-c-sreedhar-reddy** [comment]
@yawaramin the issue was ReasonReactRouter was compiled using bs < v7  and in my project I was using bs-v7. After compiling with bs-v7 it is fine.
