### ISSUE TITLE
Avoid curry for dispatch returned by useReducer

### ISSUE THREAD

**Issue by Austaras** [reasonml/reason-react#530]
I have following code 
```reason
[@react.component]
let make = () => {
  let (_, dispatch) = React.useReducer((state, _) => state + 1, 0);
  <button onClick={_e => dispatch(1)}> {ReasonReact.string("+")} </button>;
};
```
which compiles to
```js
function App(Props) {
  var match = React.useReducer((function (state, param) {
          return state + 1 | 0;
        }), 0);
  var dispatch = match[1];
  return React.createElement("button", {
              onClick: (function (_e) {
                  return Curry._1(dispatch, 1);
                })
            }, "+");
}
```
Curry for dispatch is not needed, can this be fixed or it's limited by something else?

**Comment by Austaras** [comment]
As my limited knowledge for bucklescript, maybe dispatch should be typed as `([@bs] 'action => unit)`

**Comment by johnridesabike** [comment]
This PR would address this issue #529

**Comment by Austaras** [comment]
> This PR would address this issue #529

cool, hope your pr will be merged soon

**Comment by johnridesabike** [comment]
#529 got messed up. It was merged by accident, but none of its code was actually added to the master branch. #551 re-opened it.
