### ISSUE TITLE
namespace for dom elements that's agnostic to reasonreact

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason-react#54]
Aka it'd be nice if `<div />` _post-ppx_ compiled to something like `DOM.createElement("div", ...)` rather than `ReactDOMRe.createElement("div", ...)`. It's only a name change; but this allows alternatives such as Preact to override the `DOM` part without giving the impression that these are from ReasonReact.

Technically you could just use the pre-ppx desugared JSX: https://reasonml.github.io/guide/language/jsx

but writing one's own ppx + distribute it for js compilation isn't straightforward yet, and discouraged (macros and all)

**Comment by jdhorwitz** [comment]
I can tackle this one @chenglou. Just a nudge in the right direction would be helpful.

**Comment by rickyvetter** [comment]
@jdhorwitz I think that for this update changes need to be made to two repos:

First a new ppx in BuckleScript based off of this file which will transform to DOM instead of ReactDOMRe - https://github.com/BuckleScript/bucklescript/blob/master/jscomp/bin/reactjs_ppx_2.ml

Second a new module DOM in this repo that will have the same hooks as ReactDOMRe.

**Comment by chenglou** [comment]
Thanks for the interest! But hold it for a sec. I'm iterating on something that might make this much easier.

**Comment by newtack** [comment]
I am very interested in support for Preact for mobile, while using one API (reason-react) for either React or Preact. Please let me/us know when you know more and if there is anything we can do to help accomplish this.

**Comment by peterpme** [comment]
For the sake of cleaning up the repo (and given how old this issue is) I'm going to close this out.

Please re-open if this is still relevant. Thanks!
