### ISSUE TITLE
bsrefmt version removes bs.obj externals 

### ISSUE THREAD

**Issue by rickyvetter** [reasonml/reason-react#540]
Was testing with @peterpme and at least some projects won't be able to build if we use bsrefmt that we are pinned to now. https://github.com/reasonml/reason-react/commit/abf61ee706c8b4b51172598c8a6c409716100903 for a manual fix. cc @bloodyowl as it's related to https://github.com/reasonml/reason-react/pull/539

**Comment by bloodyowl** [comment]
@rickyvetter Sorry about that, I though the minimum BuckleScript version was raised on the project. Created a PR that fixes it in the `React` module. https://github.com/reasonml/reason-react/pull/541
