### ISSUE TITLE
Stop versioning lib/js

### ISSUE THREAD

**Issue by bloodyowl** [reasonml/reason-react#548]
I'd say that the benefits no longer outgrow the negative aspects now:

- most of the code is bindings without any runtime
- when there is runtime, it creates merge conflicts
- it'd be more convenient when developing to have the build next to the source file (e.g. `src/React.bs.js`, with `*.bs.js` in gitignore)

**Comment by rickyvetter** [comment]
Yeah agreed. I don't think it's a good idea to recommend unsafe JS usage of ReasonReact as it stands today. I think we can do this in a non-breaking release if we still publish these files, or we can remove them entirely in the next breaking.

If someone takes this on don't forget about the main entry in package.json and other config files.
