### ISSUE TITLE
Docs: ReasonReact API

### ISSUE THREAD

**Issue by peterpme** [reasonml/reason-react#559]
A lot of folks have been asking about a documented ReasonReact API

- mentioning stuff that's going away / deprecated
- going through the API and at a high level, talking about each function.

There are curried versions of that function, but we should talk about them under each top level, for example:

- `useEffect`
  talk about useEffect0, useEffect1, etc, here
- `useState`

**Comment by yawaramin** [comment]
I've been thinking of adding some API docs to ReasonReact. I can take a shot at this.

**Comment by davesnx** [comment]
Closing this since it's duplicated https://github.com/reasonml/reason-react/issues/473
