### ISSUE TITLE
Enable simple "middleware" for actions/reducers

### ISSUE THREAD

**Issue by af** [reasonml/reason-react#57]
👏  on the new reducer API, it looks great!

One use-case from Redux that I would love to see enabled is centralized logging of actions; it can be tremendously useful for debugging. In Redux the way to do this is with a logging middleware, a generic function that all actions pass through on their way to the reducer. Analytics are another widely useful application for middleware, and this API could potentially allow actions to be transformed on their way through the middleware.

In Discord, @rickyvetter suggested adding an optional `reducerHook` argument [when creating a component](https://github.com/reasonml/reason-react/blob/master/src/reasonReact.re#L643). Then you could create your own component "factory" as follows:

```
let awesomeLogger action => {
  Js.log action;
  action
}

let reducerComponentWithAwesomeLogging
    debugName
    :componentSpec 'state stateless noRetainedProps noRetainedProps 'action =>
  basicComponent reducerHook::awesomeLogger debugName;
```

Obviously logging a plain variant with `Js.log` as above is not going to be super useful, it's just there to show the concept and a potential `action => action` middleware signature

**Comment by aappddeevv** [comment]
I think you can just compose your actual component handler with the "middleware" handler and use that resulting function.

**Comment by phated** [comment]
I'm not sure this makes sense with 0.7.0 since the bindings are zero-cost and React has introduced hooks.

**Comment by rickyvetter** [comment]
Yup sorry to leave this issue sitting here, but with hooks it’s now quite easy to build your own middleware ontop of useReducer. I think this is the way to go.
