### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by amiralies** [reasonml/reason-react#585]
Should we mention unicode support and unicode behavouir of strings in docs? or maybe a link to [String and char](https://reasonml.github.io/docs/en/string-and-char) ?

**Comment by rickyvetter** [comment]
Since Reason JSX syntax doesn't default to string children like JS I'm not sure that any special aside here is necessary. Unicode works exactly like it does in the rest of Reason, right?

**Comment by amiralies** [comment]
You're right.
