### ISSUE TITLE
Add support for functional components

### ISSUE THREAD

**Issue by rchanou** [reasonml/reason-react#61]
Support for function components is [on the roadmap, according to the docs](https://reasonml.github.io/reason-react/#reason-react-convert-over-reactjs-idioms-functional-component), but I didn't find any existing issue I could track, so I'm making one now. 🙂

**Comment by cullophid** [comment]
This would be great... The syntax is very verbose, and the majority of components in an app are generally functional / stateless components.

**Comment by alexfedoseev** [comment]
RR has `statelessComponent`. Same shape w/ `reducerComponent` greatly simplifies adding state in case I need it. Snippet simplifies scaffolding of component's shape.

I really like it in RR (please don't change it). JS's functions vs classes thing is terribly annoying and counterproductive.

**Comment by cullophid** [comment]
@alexfedoseev It depends on how you structure your application. If you are using a lot of stateful components the current setup is fine, but if you are using an elm style architecture you only ever need stateless components.

**Comment by cullophid** [comment]
"adding state in case its needed" made me cringe a bit. Immutability is one of the core features of the language exactly because its important that you are careful and deliberate about how where you have state.

**Comment by alexfedoseev** [comment]
In most cases, I prefer encapsulated component's state if that's what you're asking.

**Comment by phated** [comment]
This is now available in ReasonReact 0.7.0 - see https://reasonml.github.io/reason-react/docs/en/components
