### ISSUE TITLE
Order of reducer arguments is the opposite to Redux

### ISSUE THREAD

**Issue by frankwallis** [reasonml/reason-react#62]
Redux defines a reducer as:
```
function reducer(state, action)
```
But statefulComponent uses:
```
reducer: fun action state => {}
```
Is this deliberate to enable currying? Because it really tripped me up!

**Comment by chenglou** [comment]
It's deliberate. cc @cristianoc

**Comment by cristianoc** [comment]
A reducer transforms state depending on an action.
This is the current type
```
  reducer: 'action => 'state => update 'state 'retainedProps 'action,
```
Note that while the action is available immediately, state is available only later (scheduled by setState to happen some time in the future).
Passing state first, would make the reducer strictly less expressive, and prevents potential future generalizations of the state transformation type from ```'state => update 'state 'retainedProps 'action``` to something more expressive.

**Comment by chenglou** [comment]
^ There are nuances to prepare for Fiber in that btw.

Closing this. Thanks for raising the issue though!
