### ISSUE TITLE
Minimal example on ReasonReact website has an unused variable "name"

### ISSUE THREAD

**Issue by josdejong** [reasonml/reason-react#639]
The ReasonReact website (https://reasonml.github.io/reason-react/) has the following minimal example on the front page:

```reasonml
[@react.component]
let make = (~name) =>
  <button>
    {React.string("Hello!")}
  </button>;
```

Here the prop `name` is not actually used. 

Maybe it's an idea to change this to render something like `{React.string("Hello" ++ name ++ "!")}`? 

😄

**Comment by bobzhang** [comment]
sounds great, would you send a PR on this? thanks

**Comment by josdejong** [comment]
Okido, here you go: #640
