### ISSUE TITLE
Drag events

### ISSUE THREAD

**Issue by ersinakinci** [reasonml/reason-react#642]
I created a PR for more correct bindings for `onDrag`, `onDrop`, etc.: https://github.com/reasonml/reason-react/pull/641

Basically, it creates a new event type and associated module, `ReactEvent.Drag`, that's the same as `ReactEvent.Mouse.t` except it includes a binding for [`dataTransfer`](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API#Interfaces).

**Comment by davesnx** [comment]
Merged https://github.com/reasonml/reason-react/pull/641, will probably be available under 0.9.2
