### ISSUE TITLE
special character in res compile

### ISSUE THREAD

**Issue by virgiledelplace** [reasonml/reason-react#643]
Hello,

I think its not bug, i think its recommendation i need, i work on React project with rescript, but when i wrote a special character in my RES file like "é" i got "\xc3\xa9" in my bs.js file. Sur i use "string" |> React.string i fond understand, in my web render i got this : "Ã©". My editor is VSC in UTF-8 and in my html i have good meta-charset.

In advance, thanks you!

**Comment by davesnx** [comment]
ReScript recently changed the behaviour of their UTF on strings, before was needed to use "`". 

Check the playground: https://rescript-lang.org/try?code=DYUwLgBAhhC8EAMCHCBQpICM4QEQEvdUg

**Comment by davesnx** [comment]
Nothing to do in reason-react, closing.
