### ISSUE TITLE
Error: Unbound value ContextProvider.makeProps

### ISSUE THREAD

**Issue by digression99** [reasonml/reason-react#649]
Hi, I'm new to use reason-react. I happened to write a example code in the docs and I attached `include React.Context;` before my context provider to prevent `makeProps` issue, and I found it still exists.

Is there any solution to fix this error? Thank you for your help in advance!

<img width="1174" alt="Screen Shot 2021-02-08 at 8 18 27 PM" src="https://user-images.githubusercontent.com/7947600/107213386-a8ae0380-6a4b-11eb-8b09-2a0a6a134f9a.png">

I use version `0.9.1` of reason-react.

**Comment by davesnx** [comment]
I don't have any issue with React.Context, tested https://melange.re/unstable/playground/?language=Reason&code=bW9kdWxlIENQID0gewogIGxldCB0aGVtZUNvbnRleHQgPSBSZWFjdC5jcmVhdGVDb250ZXh0KCJsaWdodCIpOwoKICBpbmNsdWRlIFJlYWN0LkNvbnRleHQ7CiAgbGV0IG1ha2UgPSBSZWFjdC5Db250ZXh0LnByb3ZpZGVyKHRoZW1lQ29udGV4dCk7Cn07CgpbQHJlYWN0LmNvbXBvbmVudF0KbGV0IG1ha2UgPSAoKSA9PiA8ZGl2PiA8Q1AgdmFsdWU9ImxpZ2h0Ij4gPGRpdiAvPiA8L0NQPiA8L2Rpdj47Cg%3D%3D&live=off

Can you provide more details? Closing for now, feel free to keep asking questions thought.

**Comment by andywhite37** [comment]
Just leaving a note for any poor future visitors - I also ran into this with a much older version of `reason-react` (`^0.9.1`). You can workaround this by just implementing your own `makeProps` function by hand:

![image](https://github.com/reasonml/reason-react/assets/274734/64453773-ea19-4f6f-beaf-64260d7a8dcd)

**Comment by anmonteiro** [comment]
@andywhite37 you can also use `external makeProps` with `[@@mel.obj]` which will remove the runtime created by `let makeProps` in your example.
