### ISSUE TITLE
Possibly incorrect example?

### ISSUE THREAD

**Issue by EmperorEarth** [reasonml/reason-react#65]
Should [this](https://github.com/reasonml/reason-react/blob/c1117d98acf2694a0dd9da9d8a675961f5ac7b5b/docs/index.html#L306) be `MyDialog`? It seems to be recursively calling [itself](https://github.com/reasonml/reason-react/blob/c1117d98acf2694a0dd9da9d8a675961f5ac7b5b/docs/index.html#L293)

I could be wrong - very new to Reason

**Comment by chenglou** [comment]
You're right, thanks!
