### ISSUE TITLE
.merlin setup?

### ISSUE THREAD

**Issue by fikriauliya** [reasonml/reason-react#66]
I have followed this https://reasonml.github.io/guide/editor-tools, and my VSCode could type check the Reason Native project https://github.com/reasonml/ReasonNativeProject (with minor glitch https://github.com/reasonml-editor/vscode-reasonml/issues/76#issuecomment-331474051)

However, for this project, there are still a lot of "Unbound module errors": `Js`, `ReasonReact`. And no .merlin file exists here.

How to correctly setup Merlin for Bucklescript project? It seems `Js` and `ReasonReact` bindings are not even in `opam`?

**Comment by fikriauliya** [comment]
I managed to generate `.merlin` file by running `bsb -make-world` and VSCode can type check now :).
Feel free to close this if it is the correct way to do.
And please consider to put this in the README for the benefit of other newcomers.

**Comment by fikriauliya** [comment]
It apparently already in `npm build`. Sorry for the noise, closing

**Comment by mercantilism** [comment]
I just want to add, for whatever it's worth - not much - I did this too, twice. Somehow I just completely  keep missing the ```&& npm install && npm start``` in ```cd my-react-app && npm install && npm start```
