### ISSUE TITLE
Kicking off an action outside of a callback is awkward

### ISSUE THREAD

**Issue by jaredly** [reasonml/reason-react#68]
You have to do `(reduce (fun () => MyAction)) ()`. Would be nice to have a `reduceNonCallback` (that's a terrible name) or something...

**Comment by chenglou** [comment]
I'm thinking of something less specific and convenient, but more broadly applicable:

```reason
onClick=(self.reduceA Click)
```

So that's `onClick=(self.reduce (fun _ => Click))`

In your case you'd do `(reduceA Click ())`

What do you think? Also, `reduceT` for "token" instead of "action" would have been a nice name...

**Comment by hph** [comment]
I think I would personally prefer `reduceAction` or `reduceToken`. It's still easier to type and scan than a whole callback, and a bit more clear than `reduceA` or `reduceToken` (imo).

**Comment by rickyvetter** [comment]
Closing because we’ve had `send` for a while.
