### ISSUE TITLE
SVG Filter support

### ISSUE THREAD

**Issue by JUSTIVE** [reasonml/reason-react#681]
React supports svg filters like feblend, feflood, fematrix, etc.. (see https://github.com/facebook/react/search?q=feblend).
I can't use those tags with reason-react, seem there are no bindings for them.

**Comment by davesnx** [comment]
Hey @JUSTIVE 

All HTML tags in Reason-react (and as well React.js) are camelCase. So feBlend, feMatrix and all of the SVG tags are available under this lib.
