### ISSUE TITLE
Rich Text Editor Support Issue

### ISSUE THREAD

**Issue by emailtester11127** [reasonml/reason-react#683]
Hello  @jordwalke @chenglou 
currently  is there any way to used npm package in reasonml ?

How can we used Text editor or other npm packages like ( https://www.npmjs.com/package/react-draft-wysiwyg ) this in the reasonml.

**Comment by davesnx** [comment]
This would require to be binded such as https://kevanstannard.github.io/rescript-blog/bind-to-external-component.html. Probably all information in the ReScript documentation https://rescript-lang.org/docs. 

It seems like there's nothing that talks about binding to a ReactJS component, but should be easy to look for in google ^^
