### ISSUE TITLE
Can reason-react and the ppx be in the same package?

### ISSUE THREAD

**Issue by jchavarri** [reasonml/reason-react#739]
I wonder if we could have a single opam package for both the bindings / runtime library and the ppx, as I can't think of any situations where one would go without the other. People could include them in dune files like `reason-react.lib` and `reason-react.ppx`.

Otherwise, if 2 packages are published, I think `reason-react.opam` should be modified to include:

```
"reason-react-ppx" {= version}
```

as they are heavily coupled.

**Comment by davesnx** [comment]
Once reason-react-ppx gets published we can add `"reason-react-ppx" {= version}` to reason-react yes

**Comment by davesnx** [comment]
The solution for now is using `{= version}` and we will publish reason-react-ppx soon to opam.
