### ISSUE TITLE
error when building nix flake

### ISSUE THREAD

**Issue by joprice** [reasonml/reason-react#740]
When trying to start a shell using the nix flake, it fails when trying to access gitlabe.inria.fr, which doesn't respond for me:

```
       last 7 log lines:
       >
       > trying https://gitlab.inria.fr/api/v4/projects/fpottier%2Ffix/repository/archive.tar.gz?sha=20230505
       >   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
       >                                  Dload  Upload   Total   Spent    Left  Speed
       >   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
       > curl: (7) Failed to connect to gitlab.inria.fr port 443 after 89 ms: Couldn't connect to server
       > error: cannot download source from any mirror
```

**Comment by anmonteiro** [comment]
Yeah, the INRIA Gitlab server seems to be down. We'll host a mirror of these tarballs soon.

**Comment by joprice** [comment]
I can get a develop shell with `github:NixOS/nixpkgs/nixpkgs-unstable` and `github:nixos/nixpkg`, but not sure the build will be correct. I assume there's something that `github:nix-ocaml/nix-overlays` is providing that's needed by melange or reason-react?

**Comment by anmonteiro** [comment]
fixed https://github.com/nix-ocaml/nix-overlays/pull/913
