### ISSUE TITLE
Wrap the React Library

### ISSUE THREAD

**Issue by anmonteiro** [reasonml/reason-react#770]
reason-react exposes too many toplevel modules. These could be nested under `React`, e.g.:

- `React.DOM`
- `React.ErrorBoundary`
- `React.DOMServer`
etc

**Comment by anmonteiro** [comment]
I don't think that's a good idea. Why is it so important that our library structure matches the JS package names / sub-paths?

I actually think that the current wrapped design is quite elegant and there's a nice sub-module for everything that you can access.

**Comment by davesnx** [comment]
> I don't think that's a good idea. Why is it so important that our library structure matches the JS package names / sub-paths?

First for discoverability and second to have the minimum amount of subjectivity on the names of the structure.

**Comment by anmonteiro** [comment]
I don't think it's very discoverable having to add `(libraries react react.dom react.dom-server)` in order to have those modules appear in your editor. It's a much better API to have `(libraries reason-react)` and `React.DOM` etc. don't you think?

**Comment by davesnx** [comment]
What I'm proposing is to have `libraries reason-react` which exposes react, reactdom, etc. and not fall into the trap what we had before so, `React.Event`, `ReactDOM.Style`, `ReactDOM.Server` etc still remains wrapped.

**Comment by anmonteiro** [comment]
how do you expose those multiple toplevel modules from:

1. a single library `reason-react`
2. without exposing more?

**Comment by davesnx** [comment]
`wrapped false`, one module per toplevel, the rest either inlined or private libraries

**Comment by anmonteiro** [comment]
That actually sounds pretty nice if you can make it work. I'm in favor of it, if can manage to hide the internal modules.
