### ISSUE TITLE
Deprecate ReactDOM.render

### ISSUE THREAD

**Issue by jchavarri** [reasonml/reason-react#779]
When using `ReactDOM.render`, React.js will show these warnings at runtime:

```
    console.error
      Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
```

This can be seen in [the tests](https://github.com/reasonml/reason-react/actions/runs/6171954160/job/16751219080#step:10:21).

We should probably deprecate `ReactDOM.render` showing a similar warning, and remove them in a future version (or wait until React removes it).

**Comment by davesnx** [comment]
That sounds good, also migrate those tests 😮‍💨

**Comment by anmonteiro** [comment]
part of https://github.com/reasonml/reason-react/pull/756

**Comment by anmonteiro** [comment]
we can either add deprecations or come up with a new alert, e.g.:

```ocaml
let render = ...
[@@alert react17 "..."]
```

**Comment by jchavarri** [comment]
> part of https://github.com/reasonml/reason-react/pull/756

Oh, if we are removing `render` altogether in that PR, then I guess no deprecation step is needed?
