### ISSUE TITLE
[Website] Typography isn't very good on Linux

### ISSUE THREAD

**Issue by glennsl** [reasonml/reason-react#78]
See screenshot:

![2017-10-03-154449_1243x573_scrot](https://user-images.githubusercontent.com/5207036/31128551-75e933f2-a852-11e7-8aae-b874c683ffbe.png)

Compare this with the reasonml site:

![2017-10-03-154506_1190x654_scrot](https://user-images.githubusercontent.com/5207036/31128591-8eb70b3e-a852-11e7-86d7-5d0ba89172f9.png)

What is it supposed to look like?

**Comment by rickyvetter** [comment]
30c04c5bddf6c8f179d8b10829769a9c3c339877 should match ReasonML site. @glennsl can you confirm this looks better for you? It uses a lot of system defaults, so it's likely pretty setup dependent.

**Comment by glennsl** [comment]
The monospace font is still off. The ReasonML site uses `"SFMono-Regular", Consolas,"Roboto Mono","Droid Sans Mono","Liberation Mono",Menlo,Courier,monospace`. "Liberation Mono" is a common Linux font, and "Roboto Mono" and "Droid Sans Mono" are Android fonts that are often included in Linux Distros too I think.

**Comment by rickyvetter** [comment]
Kk. Should be good as of 5f609db4fb92f8d053ecb14361fe1e2173504924. Closing out. Please reopen or ping me if I missed something!

**Comment by glennsl** [comment]
Looks good now. Thanks!
