### ISSUE TITLE
[Docs] set up rss?

### ISSUE THREAD

**Issue by chenglou** [reasonml/reason-react#82]
cc @rickyvetter

**Comment by rickyvetter** [comment]
This is done as far as I can tell, but I'm not a heavy feed user. If you see any issues with the implementation let me know!

https://reasonml.github.io/reason-react/blog/feed.xml

<img width="959" alt="screen shot 2017-10-03 at 11 30 31 pm" src="https://user-images.githubusercontent.com/4370652/31162532-eecf3c18-a892-11e7-85f8-c5f9de7a93ff.png">

**Comment by chenglou** [comment]
Amazing, works =D
