### ISSUE TITLE
Fragment + new jsx transform

### ISSUE THREAD

**Issue by tatchi** [reasonml/reason-react#834]
Given the following code

```js
const App = () => <>hello</>
```

And using the new `jsx` transform, babel compiles it down to ([link](https://babeljs.io/repl#?browsers=%3E1%25%2C%20last%204%20versions%2C%20Firefox%20ESR%2C%20not%20dead&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=MYewdgzgLgBAggBwTAvDAFASlQPhgHhwAsBTAGzJHwHocAoBoA&debug=false&forceAllTransforms=true&modules=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=react%2Ctypescript&prettier=false&targets=&version=7.24.6&externalPlugins=&assumptions=%7B%7D))

```js
import { Fragment as _Fragment, jsx as _jsx } from "react/jsx-runtime";
const App = () => /*#__PURE__*/_jsx(_Fragment, {
  children: "hello"
});
```

While `reason-react` still uses `React.createElement` ([playground](https://melange.re/v4.0.0/playground/?language=Reason&code=W0ByZWFjdC5jb21wb25lbnRdCmxldCBtYWtlID0gKCkgPT4gPD57UmVhY3Quc3RyaW5nKCJoZWxsbyIpfTwvPgo%3D&live=off))

```js
// Generated by Melange

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function _none_(Props) {
  return React.createElement(JsxRuntime.Fragment, undefined, "hello");
}

const make = _none_;

export {
  make ,
}
/* react Not a pure module */

```

**Comment by jchavarri** [comment]
I think this issue can be closed now (thanks @tatchi !)
