### ISSUE TITLE
Lsp issue when using `[@react.component]` inside a module

### ISSUE THREAD

**Issue by benbellick** [reasonml/reason-react#853]
The Ocaml lsp seems to be broken when used with reason-react. For example, turning on the LSP and using `eglot` from within emacs, and then navigating to the first line of the below sample yields the error pasted below: 

```ocaml
module Broken = {
  [@react.component]
    let make =
    (
      ~message: string
    ) => <p> {React.string(message)} </p>;
};
```

> ⛔ Warning (jsonrpc): Invalid JSON: (unable to decode byte 0xc0 <callback> 1 193 193) {"params":{"message":"An error occured while querying ocamlformat:\nInput type: {\n  external makeProps:\n    (~message: string, ~key: string=?, unit) => {.. \"message\": string} = \"\"\n    \"����\u0000\u0000\u0000\u001b\u0000\u0000\u0000\u000b\u0000\u0000\u0000\u001e\u0000\u0000\u0000\u001d���A�'message��A�#key@��@@@\";\n  let make: {.. \"message\": string} => React.element;\n}\n\nAnswer: ocamlformat-rpc: ignoring \"<rpc input>\" (syntax error)\nFile \"<rpc input>\", line 1, characters 5-6:\nError: Syntax error\nocamlformat-rpc: ignoring \"<rpc input>\" (syntax error)\nFile \"<rpc input>\", line 1, characters 0-5:\nError: Syntax error\nocamlformat-rpc: ignoring \"<rpc input>\" (syntax error)\nFile \"<rpc input>\", line 1, characters 5-6:\nError: Syntax error\nocamlformat-rpc: ignoring \"<rpc input>\" (syntax error)\nFile \"<rpc input>\", line 1, characters 0-1:\nError: Syntax error\nocamlformat-rpc: ignoring \"<rpc input>\" (syntax error)\nFile \"<rpc input>\", line 1, characters 0-1:\nError: Syntax error\nocamlformat-rpc: ignoring \"<rpc input>\" (syntax error)\nFile \"<rpc input>\", line 1, characters 0-1:\nError: Syntax error\nocamlformat-rpc: ignoring \"<rpc input>\" (syntax error)\nFile \"<rpc input>\", line 2, characters 2-10:\nError: Syntax error\nocamlformat-rpc: ignoring \"<rpc input>\" (syntax error)\nFile \"<rpc input>\", line 2, characters 2-10:\nError: Syntax error\n","type":2},"method":"window/logMessage","js

Not sure if the problem is here or somewhere upstream, but wanted to get it down somewhere. Thanks!

versions:
ocaml-lsp-server: 1.17.0
reason-react: 0.14.0
reason-react-ppx: 0.14.0
dune: 3.15.2
melange: 3.0.0-51

**Comment by davesnx** [comment]
Can you specify the dune and melange versions?

**Comment by benbellick** [comment]
Edited to include them!

**Comment by benbellick** [comment]
Thanks for the responses. 
With the exact versions, the error still persists. 
```
[jsonrpc] (warning) Invalid JSON: (unable to decode byte 0xc0 <callback> 1 156 156) 
...
```

I believe that that related issue though may be the core of the issue. Thanks
