### ISSUE TITLE
Links going to a 404 with props-spread

### ISSUE THREAD

**Issue by kutyel** [reasonml/reason-react#88]
Both in `docs/props-spread.md` and in `docs/clone-element.md` there is a dead link to *props-spread*, is this section deliberately removed from the docs? Or has just been moved? If that is the case, I would really want to prove a PR helping to fix the docs! 😄

**Comment by rickyvetter** [comment]
I fixed the clone-element broken link here - 9b5ec7a4385e14e5ff228d5eb2372488a661fbf4.

It looks like the convert.md file got removed in 5123c0dc2d8ddfc1317c41f3ffcb64e688b37105. I don't see where the relevant sections have been moved so I'm not sure on best direction here. There are a number of docs pointing to that file though, so we should clean up all of them.

**Comment by kutyel** [comment]
Maybe @jordwalke or @chenglou can give us a hint? 😉

**Comment by chenglou** [comment]
Fixed, thanks!

**Comment by kutyel** [comment]
@chenglou You are welcome, I would have preferred to do the PR myself though, I'd like to contribute to the project 😉

**Comment by chenglou** [comment]
Plenty of contribution opportunities left! https://reasonml.github.io/reason-react/docs/en/roadmap.html#your-contribution-opportunities and https://reasonml.github.io/community/roadmap#your-contribution-opportunities
