### ISSUE TITLE
`willMount` for server side rendering

### ISSUE THREAD

**Issue by viebel** [reasonml/reason-react#95]
In React Server side rendering, `componentDidMount` is not triggered.
On the other hand,  ReasonReact doesn't have `willMount` but  only `didMount`.
 
What can I do if I need `componentDidMount` in server side?

**Comment by chenglou** [comment]
Can you also list one concrete use-case please? Just for reference

**Comment by viebel** [comment]
My use case is that I want to create component that updates the page title.
Something like that:
`<Title title="my article" />`

The implementation in client side to call the side-effect inside `didMount`.

But, `didMount` is not triggered in server side rendering.

**Comment by maarekj** [comment]
Do put the code in the _constructor_ is enough?

**Comment by chenglou** [comment]
Note that this wouldn't work with streaming, in reactjs, anyway

**Comment by maarekj** [comment]
Yes, but streaming is optional. No ?

**Comment by maarekj** [comment]
Finally it's planned to add willMount?

**Comment by nabati** [comment]
> My use case is that I want to create component that updates the page title.
> Something like that:
> <Title title="my article" />

Instead of imperatively updating the title once the component has been mounted, how about rendering the correct title from the beginning? This could possibly hint to somewhere where you could improve your design.

Also, in ReactJS, none of the lifecycle-hooks are run on server rendering AFAIK.

**Comment by maarekj** [comment]
Precisely, the lifecycle-hook `UNSAFE_componentWillMount` is the only lifecycle-hook to fire on the **server**, **before** the component is mounted.

**Comment by rickyvetter** [comment]
I think SSR is fully supported with hooks. We aren’t planning on adding features to the record api.
